In [10]:
from dotenv import load_dotenv
import os
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
import pandas as pd

load_dotenv()

SPOTIFY_CLIENT_ID = os.getenv("SPOTIFY_CLIENT_ID")
SPOTIFY_CLIENT_SECRET  = os.getenv("SPOTIFY_CLIENT_SECRET")

In [11]:
print(SPOTIFY_CLIENT_ID, SPOTIFY_CLIENT_SECRET)

91fc5293d97547f9928d683467e94482 eaa92f897bba4150bbb01d0f1f9d636e

In [12]:
client_credentials_manager = SpotifyClientCredentials(client_id = SPOTIFY_CLIENT_ID, client_secret= SPOTIFY_CLIENT_SECRET)

In [13]:
sp = spotipy.Spotify(client_credentials_manager=client_credentials_manager)

In [14]:
playlist_link = "https://open.spotify.com/playlist/6VOedaf3eNWDOVpa9Qdlvg"

In [15]:
playlist_link.split('/')[-1]

'6VOedaf3eNWDOVpa9Qdlvg'

In [16]:
playlist_URI = playlist_link.split('/')[-1]

In [17]:
data = sp.playlist_tracks(playlist_id=playlist_URI)

In [18]:
data.keys()

dict_keys(['href', 'items', 'limit', 'next', 'offset', 'previous', 'total'])

In [45]:
data['items'][0]

{'added_at': '2025-05-10T16:34:06Z',
 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/31rzz7jr6t3e3mqgitwppkmfg2ve'},
  'href': 'https://api.spotify.com/v1/users/31rzz7jr6t3e3mqgitwppkmfg2ve',
  'id': '31rzz7jr6t3e3mqgitwppkmfg2ve',
  'type': 'user',
  'uri': 'spotify:user:31rzz7jr6t3e3mqgitwppkmfg2ve'},
 'is_local': False,
 'primary_color': None,
 'track': {'preview_url': None,
  'available_markets': ['AR',
   'AU',
   'AT',
   'BE',
   'BO',
   'BR',
   'BG',
   'CA',
   'CL',
   'CO',
   'CR',
   'CY',
   'CZ',
   'DK',
   'DO',
   'DE',
   'EC',
   'EE',
   'SV',
   'FI',
   'FR',
   'GR',
   'GT',
   'HN',
   'HK',
   'HU',
   'IS',
   'IE',
   'IT',
   'LV',
   'LT',
   'LU',
   'MY',
   'MT',
   'MX',
   'NL',
   'NZ',
   'NI',
   'NO',
   'PA',
   'PY',
   'PE',
   'PH',
   'PL',
   'PT',
   'SG',
   'SK',
   'ES',
   'SE',
   'CH',
   'TW',
   'TR',
   'UY',
   'US',
   'GB',
   'AD',
   'LI',
   'MC',
   'ID',
   'JP',
   'TH',
   'VN',
   'RO',
   'IL',
   'ZA',
   'SA',
   'AE',
   'BH',
   'QA',
   'OM',
   'KW',
   'EG',
   'MA',
   'DZ',
   'TN',
   'LB',
   'JO',
   'PS',
   'IN',
   'BY',
   'KZ',
   'MD',
   'UA',
   'AL',
   'BA',
   'HR',
   'ME',
   'MK',
   'RS',
   'SI',
   'KR',
   'BD',
   'PK',
   'LK',
   'GH',
   'KE',
   'NG',
   'TZ',
   'UG',
   'AG',
   'AM',
   'BS',
   'BB',
   'BZ',
   'BT',
   'BW',
   'BF',
   'CV',
   'CW',
   'DM',
   'FJ',
   'GM',
   'GE',
   'GD',
   'GW',
   'GY',
   'HT',
   'JM',
   'KI',
   'LS',
   'LR',
   'MW',
   'MV',
   'ML',
   'MH',
   'FM',
   'NA',
   'NR',
   'NE',
   'PW',
   'PG',
   'PR',
   'WS',
   'SM',
   'ST',
   'SN',
   'SC',
   'SL',
   'SB',
   'KN',
   'LC',
   'VC',
   'SR',
   'TL',
   'TO',
   'TT',
   'TV',
   'VU',
   'AZ',
   'BN',
   'BI',
   'KH',
   'CM',
   'TD',
   'KM',
   'GQ',
   'SZ',
   'GA',
   'GN',
   'KG',
   'LA',
   'MO',
   'MR',
   'MN',
   'NP',
   'RW',
   'TG',
   'UZ',
   'ZW',
   'BJ',
   'MG',
   'MU',
   'MZ',
   'AO',
   'CI',
   'DJ',
   'ZM',
   'CD',
   'CG',
   'IQ',
   'LY',
   'TJ',
   'VE',
   'ET',
   'XK'],
  'explicit': False,
  'type': 'track',
  'episode': False,
  'track': True,
  'album': {'available_markets': ['AR',
    'AU',
    'AT',
    'BE',
    'BO',
    'BR',
    'BG',
    'CA',
    'CL',
    'CO',
    'CR',
    'CY',
    'CZ',
    'DK',
    'DO',
    'DE',
    'EC',
    'EE',
    'SV',
    'FI',
    'FR',
    'GR',
    'GT',
    'HN',
    'HK',
    'HU',
    'IS',
    'IE',
    'IT',
    'LV',
    'LT',
    'LU',
    'MY',
    'MT',
    'MX',
    'NL',
    'NZ',
    'NI',
    'NO',
    'PA',
    'PY',
    'PE',
    'PH',
    'PL',
    'PT',
    'SG',
    'SK',
    'ES',
    'SE',
    'CH',
    'TW',
    'TR',
    'UY',
    'US',
    'GB',
    'AD',
    'LI',
    'MC',
    'ID',
    'JP',
    'TH',
    'VN',
    'RO',
    'IL',
    'ZA',
    'SA',
    'AE',
    'BH',
    'QA',
    'OM',
    'KW',
    'EG',
    'MA',
    'DZ',
    'TN',
    'LB',
    'JO',
    'PS',
    'IN',
    'BY',
    'KZ',
    'MD',
    'UA',
    'AL',
    'BA',
    'HR',
    'ME',
    'MK',
    'RS',
    'SI',
    'KR',
    'BD',
    'PK',
    'LK',
    'GH',
    'KE',
    'NG',
    'TZ',
    'UG',
    'AG',
    'AM',
    'BS',
    'BB',
    'BZ',
    'BT',
    'BW',
    'BF',
    'CV',
    'CW',
    'DM',
    'FJ',
    'GM',
    'GE',
    'GD',
    'GW',
    'GY',
    'HT',
    'JM',
    'KI',
    'LS',
    'LR',
    'MW',
    'MV',
    'ML',
    'MH',
    'FM',
    'NA',
    'NR',
    'NE',
    'PW',
    'PG',
    'PR',
    'WS',
    'SM',
    'ST',
    'SN',
    'SC',
    'SL',
    'SB',
    'KN',
    'LC',
    'VC',
    'SR',
    'TL',
    'TO',
    'TT',
    'TV',
    'VU',
    'AZ',
    'BN',
    'BI',
    'KH',
    'CM',
    'TD',
    'KM',
    'GQ',
    'SZ',
    'GA',
    'GN',
    'KG',
    'LA',
    'MO',
    'MR',
    'MN',
    'NP',
    'RW',
    'TG',
    'UZ',
    'ZW',
    'BJ',
    'MG',
    'MU',
    'MZ',
    'AO',
    'CI',
    'DJ',
    'ZM',
    'CD',
    'CG',
    'IQ',
    'LY',
    'TJ',
    'VE',
    'ET',
    'XK'],
   'type': 'album',
   'album_type': 'single',
   'href': 'https://api.spotify.com/v1/albums/0I7096R74VFP2xnMmp33sY',
   'id': '0I7096R74VFP2xnMmp33sY',
   'images': [{'height': 640,
     'url': 'https://i.scdn.co/image/ab67616d0000b27336385e0fad3c87e8e8f19071',
     'width': 640},
    {'height': 300,
     'url': 'https://i.scdn.co/image/ab67616d00001e0236385e0fad3c87e8e8f19071',
     'width': 300},
    {'height': 64,
     'url': 'https://i.scdn.co/image/ab67616d0000485136385e0fad3c87e8e8f19071',
     'width': 64}],
   'name': 'PASSO BEM SOLTO',
   'release_date': '2024-04-23',
   'release_date_precision': 'day',
   'uri': 'spotify:album:0I7096R74VFP2xnMmp33sY',
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5SCDfg1YoEfI5gFtXqEWah'},
     'href': 'https://api.spotify.com/v1/artists/5SCDfg1YoEfI5gFtXqEWah',
     'id': '5SCDfg1YoEfI5gFtXqEWah',
     'name': 'ATLXS',
     'type': 'artist',
     'uri': 'spotify:artist:5SCDfg1YoEfI5gFtXqEWah'}],
   'external_urls': {'spotify': 'https://open.spotify.com/album/0I7096R74VFP2xnMmp33sY'},
   'total_tracks': 5},
  'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5SCDfg1YoEfI5gFtXqEWah'},
    'href': 'https://api.spotify.com/v1/artists/5SCDfg1YoEfI5gFtXqEWah',
    'id': '5SCDfg1YoEfI5gFtXqEWah',
    'name': 'ATLXS',
    'type': 'artist',
    'uri': 'spotify:artist:5SCDfg1YoEfI5gFtXqEWah'}],
  'disc_number': 1,
  'track_number': 3,
  'duration_ms': 116072,
  'external_ids': {'isrc': 'AUMEV2448907'},
  'external_urls': {'spotify': 'https://open.spotify.com/track/4sTlQPMyoFMPdhAJvErBN3'},
  'href': 'https://api.spotify.com/v1/tracks/4sTlQPMyoFMPdhAJvErBN3',
  'id': '4sTlQPMyoFMPdhAJvErBN3',
  'name': 'PASSO BEM SOLTO - Slowed',
  'popularity': 82,
  'uri': 'spotify:track:4sTlQPMyoFMPdhAJvErBN3',
  'is_local': False},
 'item': {'preview_url': None,
  'available_markets': ['AR',
   'AU',
   'AT',
   'BE',
   'BO',
   'BR',
   'BG',
   'CA',
   'CL',
   'CO',
   'CR',
   'CY',
   'CZ',
   'DK',
   'DO',
   'DE',
   'EC',
   'EE',
   'SV',
   'FI',
   'FR',
   'GR',
   'GT',
   'HN',
   'HK',
   'HU',
   'IS',
   'IE',
   'IT',
   'LV',
   'LT',
   'LU',
   'MY',
   'MT',
   'MX',
   'NL',
   'NZ',
   'NI',
   'NO',
   'PA',
   'PY',
   'PE',
   'PH',
   'PL',
   'PT',
   'SG',
   'SK',
   'ES',
   'SE',
   'CH',
   'TW',
   'TR',
   'UY',
   'US',
   'GB',
   'AD',
   'LI',
   'MC',
   'ID',
   'JP',
   'TH',
   'VN',
   'RO',
   'IL',
   'ZA',
   'SA',
   'AE',
   'BH',
   'QA',
   'OM',
   'KW',
   'EG',
   'MA',
   'DZ',
   'TN',
   'LB',
   'JO',
   'PS',
   'IN',
   'BY',
   'KZ',
   'MD',
   'UA',
   'AL',
   'BA',
   'HR',
   'ME',
   'MK',
   'RS',
   'SI',
   'KR',
   'BD',
   'PK',
   'LK',
   'GH',
   'KE',
   'NG',
   'TZ',
   'UG',
   'AG',
   'AM',
   'BS',
   'BB',
   'BZ',
   'BT',
   'BW',
   'BF',
   'CV',
   'CW',
   'DM',
   'FJ',
   'GM',
   'GE',
   'GD',
   'GW',
   'GY',
   'HT',
   'JM',
   'KI',
   'LS',
   'LR',
   'MW',
   'MV',
   'ML',
   'MH',
   'FM',
   'NA',
   'NR',
   'NE',
   'PW',
   'PG',
   'PR',
   'WS',
   'SM',
   'ST',
   'SN',
   'SC',
   'SL',
   'SB',
   'KN',
   'LC',
   'VC',
   'SR',
   'TL',
   'TO',
   'TT',
   'TV',
   'VU',
   'AZ',
   'BN',
   'BI',
   'KH',
   'CM',
   'TD',
   'KM',
   'GQ',
   'SZ',
   'GA',
   'GN',
   'KG',
   'LA',
   'MO',
   'MR',
   'MN',
   'NP',
   'RW',
   'TG',
   'UZ',
   'ZW',
   'BJ',
   'MG',
   'MU',
   'MZ',
   'AO',
   'CI',
   'DJ',
   'ZM',
   'CD',
   'CG',
   'IQ',
   'LY',
   'TJ',
   'VE',
   'ET',
   'XK'],
  'explicit': False,
  'type': 'track',
  'episode': False,
  'track': True,
  'album': {'available_markets': ['AR',
    'AU',
    'AT',
    'BE',
    'BO',
    'BR',
    'BG',
    'CA',
    'CL',
    'CO',
    'CR',
    'CY',
    'CZ',
    'DK',
    'DO',
    'DE',
    'EC',
    'EE',
    'SV',
    'FI',
    'FR',
    'GR',
    'GT',
    'HN',
    'HK',
    'HU',
    'IS',
    'IE',
    'IT',
    'LV',
    'LT',
    'LU',
    'MY',
    'MT',
    'MX',
    'NL',
    'NZ',
    'NI',
    'NO',
    'PA',
    'PY',
    'PE',
    'PH',
    'PL',
    'PT',
    'SG',
    'SK',
    'ES',
    'SE',
    'CH',
    'TW',
    'TR',
    'UY',
    'US',
    'GB',
    'AD',
    'LI',
    'MC',
    'ID',
    'JP',
    'TH',
    'VN',
    'RO',
    'IL',
    'ZA',
    'SA',
    'AE',
    'BH',
    'QA',
    'OM',
    'KW',
    'EG',
    'MA',
    'DZ',
    'TN',
    'LB',
    'JO',
    'PS',
    'IN',
    'BY',
    'KZ',
    'MD',
    'UA',
    'AL',
    'BA',
    'HR',
    'ME',
    'MK',
    'RS',
    'SI',
    'KR',
    'BD',
    'PK',
    'LK',
    'GH',
    'KE',
    'NG',
    'TZ',
    'UG',
    'AG',
    'AM',
    'BS',
    'BB',
    'BZ',
    'BT',
    'BW',
    'BF',
    'CV',
    'CW',
    'DM',
    'FJ',
    'GM',
    'GE',
    'GD',
    'GW',
    'GY',
    'HT',
    'JM',
    'KI',
    'LS',
    'LR',
    'MW',
    'MV',
    'ML',
    'MH',
    'FM',
    'NA',
    'NR',
    'NE',
    'PW',
    'PG',
    'PR',
    'WS',
    'SM',
    'ST',
    'SN',
    'SC',
    'SL',
    'SB',
    'KN',
    'LC',
    'VC',
    'SR',
    'TL',
    'TO',
    'TT',
    'TV',
    'VU',
    'AZ',
    'BN',
    'BI',
    'KH',
    'CM',
    'TD',
    'KM',
    'GQ',
    'SZ',
    'GA',
    'GN',
    'KG',
    'LA',
    'MO',
    'MR',
    'MN',
    'NP',
    'RW',
    'TG',
    'UZ',
    'ZW',
    'BJ',
    'MG',
    'MU',
    'MZ',
    'AO',
    'CI',
    'DJ',
    'ZM',
    'CD',
    'CG',
    'IQ',
    'LY',
    'TJ',
    'VE',
    'ET',
    'XK'],
   'type': 'album',
   'album_type': 'single',
   'href': 'https://api.spotify.com/v1/albums/0I7096R74VFP2xnMmp33sY',
   'id': '0I7096R74VFP2xnMmp33sY',
   'images': [{'height': 640,
     'url': 'https://i.scdn.co/image/ab67616d0000b27336385e0fad3c87e8e8f19071',
     'width': 640},
    {'height': 300,
     'url': 'https://i.scdn.co/image/ab67616d00001e0236385e0fad3c87e8e8f19071',
     'width': 300},
    {'height': 64,
     'url': 'https://i.scdn.co/image/ab67616d0000485136385e0fad3c87e8e8f19071',
     'width': 64}],
   'name': 'PASSO BEM SOLTO',
   'release_date': '2024-04-23',
   'release_date_precision': 'day',
   'uri': 'spotify:album:0I7096R74VFP2xnMmp33sY',
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5SCDfg1YoEfI5gFtXqEWah'},
     'href': 'https://api.spotify.com/v1/artists/5SCDfg1YoEfI5gFtXqEWah',
     'id': '5SCDfg1YoEfI5gFtXqEWah',
     'name': 'ATLXS',
     'type': 'artist',
     'uri': 'spotify:artist:5SCDfg1YoEfI5gFtXqEWah'}],
   'external_urls': {'spotify': 'https://open.spotify.com/album/0I7096R74VFP2xnMmp33sY'},
   'total_tracks': 5},
  'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5SCDfg1YoEfI5gFtXqEWah'},
    'href': 'https://api.spotify.com/v1/artists/5SCDfg1YoEfI5gFtXqEWah',
    'id': '5SCDfg1YoEfI5gFtXqEWah',
    'name': 'ATLXS',
    'type': 'artist',
    'uri': 'spotify:artist:5SCDfg1YoEfI5gFtXqEWah'}],
  'disc_number': 1,
  'track_number': 3,
  'duration_ms': 116072,
  'external_ids': {'isrc': 'AUMEV2448907'},
  'external_urls': {'spotify': 'https://open.spotify.com/track/4sTlQPMyoFMPdhAJvErBN3'},
  'href': 'https://api.spotify.com/v1/tracks/4sTlQPMyoFMPdhAJvErBN3',
  'id': '4sTlQPMyoFMPdhAJvErBN3',
  'name': 'PASSO BEM SOLTO - Slowed',
  'popularity': 82,
  'uri': 'spotify:track:4sTlQPMyoFMPdhAJvErBN3',
  'is_local': False},
 'video_thumbnail': {'url': None}}

In [10]:
len(data['items'])

88

In [49]:
data['items'][0].keys()

dict_keys(['added_at', 'added_by', 'is_local', 'primary_color', 'track', 'item', 'video_thumbnail'])

In [52]:
data['items'][0]['track'].keys()

dict_keys(['preview_url', 'available_markets', 'explicit', 'type', 'episode', 'track', 'album', 'artists', 'disc_number', 'track_number', 'duration_ms', 'external_ids', 'external_urls', 'href', 'id', 'name', 'popularity', 'uri', 'is_local'])

In [54]:
data['items'][0]['track']['album']['id']

'0I7096R74VFP2xnMmp33sY'

In [55]:
data['items'][0]['track']['album']['name']

'PASSO BEM SOLTO'

In [59]:
data['items'][0]['track']['album']['release_date']

'2024-04-23'

In [63]:
data['items'][0]['track']['album']['external_urls']['spotify']

'https://open.spotify.com/album/0I7096R74VFP2xnMmp33sY'

In [64]:
data['items'][0]['track']['album']['total_tracks']

5

In [73]:
album_list = []
for row in data['items']:
    album_id = row['track']['album']['id']
    album_name = row['track']['album']['name']
    album_release_date = row['track']['album']['release_date']
    album_total_tracks = row['track']['album']['total_tracks']
    album_url = row['track']['album']['external_urls']['spotify']
    album_element = {'album_id': album_id, 
                     'album_name' : album_name, 
                     'album_release_date' : album_release_date, 
                     'album_total_tracks' : album_total_tracks,
                     'album_url' : album_url} 
    album_list.append(album_element)

In [74]:
album_list

[{'album_id': '0I7096R74VFP2xnMmp33sY',
  'album_name': 'PASSO BEM SOLTO',
  'album_release_date': '2024-04-23',
  'album_total_tracks': 5,
  'album_url': 'https://open.spotify.com/album/0I7096R74VFP2xnMmp33sY'},
 {'album_id': '7FsRROosPNliIsu3YzSs9n',
  'album_name': 'MONTAGEM RUGADA',
  'album_release_date': '2025-08-27',
  'album_total_tracks': 6,
  'album_url': 'https://open.spotify.com/album/7FsRROosPNliIsu3YzSs9n'},
 {'album_id': '5kB03HrxWnYPPB9BvwbYG1',
  'album_name': 'NO BATIDÃO',
  'album_release_date': '2025-09-05',
  'album_total_tracks': 3,
  'album_url': 'https://open.spotify.com/album/5kB03HrxWnYPPB9BvwbYG1'},
 {'album_id': '5k8jDV518pIk74gBsU72fi',
  'album_name': 'MONTAGEM COMA',
  'album_release_date': '2025-06-06',
  'album_total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/5k8jDV518pIk74gBsU72fi'},
 {'album_id': '6L63sOxoncxwRrf2ktyudM',
  'album_name': 'OLHA MENSAGEM',
  'album_release_date': '2025-04-16',
  'album_total_tracks': 6,
  'album_url': 'https://open.spotify.com/album/6L63sOxoncxwRrf2ktyudM'},
 {'album_id': '6xUYw5goKIoyJQi9C27UBy',
  'album_name': 'NUNCA MUDA?',
  'album_release_date': '2025-01-09',
  'album_total_tracks': 6,
  'album_url': 'https://open.spotify.com/album/6xUYw5goKIoyJQi9C27UBy'},
 {'album_id': '0fauumBf19hArK8Wt3XhkC',
  'album_name': 'Montagem Supersonic',
  'album_release_date': '2025-07-04',
  'album_total_tracks': 5,
  'album_url': 'https://open.spotify.com/album/0fauumBf19hArK8Wt3XhkC'},
 {'album_id': '3bT53CJPMsSXSn0vDAX2Do',
  'album_name': 'DIA DELÍCIA',
  'album_release_date': '2025-04-25',
  'album_total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/3bT53CJPMsSXSn0vDAX2Do'},
 {'album_id': '5Y2vzkYDib5UppMXIy7SD7',
  'album_name': 'BELONG TO ME FUNK',
  'album_release_date': '2025-08-08',
  'album_total_tracks': 5,
  'album_url': 'https://open.spotify.com/album/5Y2vzkYDib5UppMXIy7SD7'},
 {'album_id': '0Qi6ZoqjRHB9W3yZl5Jb25',
  'album_name': 'Amor Na Praia',
  'album_release_date': '2025-03-26',
  'album_total_tracks': 5,
  'album_url': 'https://open.spotify.com/album/0Qi6ZoqjRHB9W3yZl5Jb25'},
 {'album_id': '4s7LxMlh6RxgdMhldfMe8u',
  'album_name': 'Funk de Beleza',
  'album_release_date': '2024-10-04',
  'album_total_tracks': 3,
  'album_url': 'https://open.spotify.com/album/4s7LxMlh6RxgdMhldfMe8u'},
 {'album_id': '5fvUS8yHMCkTZj4sJ0FHDV',
  'album_name': 'Vem Vem',
  'album_release_date': '2025-05-30',
  'album_total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/5fvUS8yHMCkTZj4sJ0FHDV'},
 {'album_id': '4QfLTUyV4lZPxoEt0BykuQ',
  'album_name': 'ACELERADA',
  'album_release_date': '2025-06-27',
  'album_total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/4QfLTUyV4lZPxoEt0BykuQ'},
 {'album_id': '5D17Gk0J7jPXLvWMszqijF',
  'album_name': 'MONTAGEM TOMADA',
  'album_release_date': '2025-03-21',
  'album_total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/5D17Gk0J7jPXLvWMszqijF'},
 {'album_id': '2JCCZCrAWvohxlUXRRz36I',
  'album_name': 'COM MEDO!',
  'album_release_date': '2025-03-06',
  'album_total_tracks': 5,
  'album_url': 'https://open.spotify.com/album/2JCCZCrAWvohxlUXRRz36I'},
 {'album_id': '3JsABNfp6sTjgcawWxzmj7',
  'album_name': 'MONTAGEM XONADA',
  'album_release_date': '2025-07-02',
  'album_total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/3JsABNfp6sTjgcawWxzmj7'},
 {'album_id': '3gciIH7IvN83uLz6Ay983i',
  'album_name': 'FUNK SIGILO',
  'album_release_date': '2025-03-14',
  'album_total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/3gciIH7IvN83uLz6Ay983i'},
 {'album_id': '4ZopuwBxqYKDYkKh61tNqv',
  'album_name': 'MENTE MÁ',
  'album_release_date': '2025-05-16',
  'album_total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/4ZopuwBxqYKDYkKh61tNqv'},
 {'album_id': '5g6rpHaTCaF9tXWfiHd2Cr',
  'album_name': 'MONTAGEM BATCHI',
  'album_release_date': '2025-04-11',
  'album_total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/5g6rpHaTCaF9tXWfiHd2Cr'},
 {'album_id': '2VW8krMRkhGJmdlcHbyTfZ',
  'album_name': 'MONTAGEM BAILÃO',
  'album_release_date': '2025-04-04',
  'album_total_tracks': 5,
  'album_url': 'https://open.spotify.com/album/2VW8krMRkhGJmdlcHbyTfZ'},
 {'album_id': '0Qi6ZoqjRHB9W3yZl5Jb25',
  'album_name': 'Amor Na Praia',
  'album_release_date': '2025-03-26',
  'album_total_tracks': 5,
  'album_url': 'https://open.spotify.com/album/0Qi6ZoqjRHB9W3yZl5Jb25'},
 {'album_id': '6dNugoBYWvUDQDtLurImhw',
  'album_name': 'X-TALI',
  'album_release_date': '2024-08-23',
  'album_total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/6dNugoBYWvUDQDtLurImhw'},
 {'album_id': '1kmsUHDC0n611meNgzRkuw',
  'album_name': 'FUNK UNIVERSO',
  'album_release_date': '2024-07-03',
  'album_total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/1kmsUHDC0n611meNgzRkuw'},
 {'album_id': '7CWmZcjCHJWd7detYptzAX',
  'album_name': 'LOS VOLTAJE',
  'album_release_date': '2025-04-11',
  'album_total_tracks': 5,
  'album_url': 'https://open.spotify.com/album/7CWmZcjCHJWd7detYptzAX'},
 {'album_id': '2acEAXK1zIr0cPBkIDDJgz',
  'album_name': 'LUNA BALA',
  'album_release_date': '2025-04-18',
  'album_total_tracks': 6,
  'album_url': 'https://open.spotify.com/album/2acEAXK1zIr0cPBkIDDJgz'},
 {'album_id': '62R2H85ZiKLp0lYHPprQWV',
  'album_name': 'MTG - RITMO ZELDA',
  'album_release_date': '2024-06-28',
  'album_total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/62R2H85ZiKLp0lYHPprQWV'},
 {'album_id': '4FRxgE6LA2UGJ5yz8diaI9',
  'album_name': 'FUNKED UP',
  'album_release_date': '2024-01-19',
  'album_total_tracks': 3,
  'album_url': 'https://open.spotify.com/album/4FRxgE6LA2UGJ5yz8diaI9'},
 {'album_id': '6Zd0Hg3HKVH7xhBPgESQy1',
  'album_name': 'FUNK DO BOUNCE (Slowed)',
  'album_release_date': '2024-08-30',
  'album_total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/6Zd0Hg3HKVH7xhBPgESQy1'},
 {'album_id': '1QFKbF3Oot9Ad1NnRCAG32',
  'album_name': 'X-SLIDE',
  'album_release_date': '2024-05-10',
  'album_total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/1QFKbF3Oot9Ad1NnRCAG32'},
 {'album_id': '3tSeUNn7yOQPEex7jwS9Bf',
  'album_name': 'GLORY',
  'album_release_date': '2024-05-24',
  'album_total_tracks': 3,
  'album_url': 'https://open.spotify.com/album/3tSeUNn7yOQPEex7jwS9Bf'},
 {'album_id': '4QmDrxVGw99LUJOubfPJz9',
  'album_name': 'SPOOKY',
  'album_release_date': '2024-10-24',
  'album_total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/4QmDrxVGw99LUJOubfPJz9'},
 {'album_id': '1qlnjo9SZtK01FqDyjv6nM',
  'album_name': 'EI DO SENSACIO!',
  'album_release_date': '2024-07-29',
  'album_total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/1qlnjo9SZtK01FqDyjv6nM'},
 {'album_id': '06a7H7nusNMvM7yL8m3fy1',
  'album_name': 'AURA',
  'album_release_date': '2024-07-12',
  'album_total_tracks': 3,
  'album_url': 'https://open.spotify.com/album/06a7H7nusNMvM7yL8m3fy1'},
 {'album_id': '5rDznSixlUXNxJySfWQNb7',
  'album_name': 'REI DO BRASIL',
  'album_release_date': '2023-06-02',
  'album_total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/5rDznSixlUXNxJySfWQNb7'},
 {'album_id': '1vQpZhp0nRdlUT4m2cgV4k',
  'album_name': 'Mexican Phonk Eki',
  'album_release_date': '2023-06-23',
  'album_total_tracks': 3,
  'album_url': 'https://open.spotify.com/album/1vQpZhp0nRdlUT4m2cgV4k'},
 {'album_id': '5n9EF7hP2GRMiklzLpPY0E',
  'album_name': 'AVANGARD (Slowed)',
  'album_release_date': '2024-08-02',
  'album_total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/5n9EF7hP2GRMiklzLpPY0E'},
 {'album_id': '2Osz2h7ZjKHOZh5grL7o6G',
  'album_name': 'BAIXO',
  'album_release_date': '2023-09-19',
  'album_total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/2Osz2h7ZjKHOZh5grL7o6G'},
 {'album_id': '1k9oQsBjwIhc4vF32zxvY5',
  'album_name': 'NEXT!',
  'album_release_date': '2024-06-07',
  'album_total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/1k9oQsBjwIhc4vF32zxvY5'},
 {'album_id': '27XmqsKeLyr5jDURAordcd',
  'album_name': 'TUCA DONKA',
  'album_release_date': '2023-07-28',
  'album_total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/27XmqsKeLyr5jDURAordcd'},
 {'album_id': '7JslfZtjZ430btdARyxLQ4',
  'album_name': 'PYTHON FUNK',
  'album_release_date': '2024-08-23',
  'album_total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/7JslfZtjZ430btdARyxLQ4'},
 {'album_id': '6DptPhwLku8xvWBodULnC6',
  'album_name': 'Orquestra Maldita',
  'album_release_date': '2023-06-15',
  'album_total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/6DptPhwLku8xvWBodULnC6'},
 {'album_id': '1ILssfrknV8cQv5QvwBGUY',
  'album_name': 'DNA',
  'album_release_date': '2023-12-21',
  'album_total_tracks': 3,
  'album_url': 'https://open.spotify.com/album/1ILssfrknV8cQv5QvwBGUY'},
 {'album_id': '6tf2ziKDZQJinItJi99wBW',
  'album_name': 'SPACE!',
  'album_release_date': '2024-04-26',
  'album_total_tracks': 3,
  'album_url': 'https://open.spotify.com/album/6tf2ziKDZQJinItJi99wBW'},
 {'album_id': '3BsuqyYCV0DYIBrDi1SKwQ',
  'album_name': 'Sequência da Dz7',
  'album_release_date': '2023-05-07',
  'album_total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/3BsuqyYCV0DYIBrDi1SKwQ'},
 {'album_id': '2EuOCirl08WxbRY2cfj4H5',
  'album_name': 'Life in Rio',
  'album_release_date': '2023-03-17',
  'album_total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/2EuOCirl08WxbRY2cfj4H5'},
 {'album_id': '3Iw0jAPzwgmuqSIWQa9i8W',
  'album_name': 'FUNK INFERNAL',
  'album_release_date': '2024-09-27',
  'album_total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/3Iw0jAPzwgmuqSIWQa9i8W'},
 {'album_id': '1R1KJCX1oc3xqSbABo2Wpn',
  'album_name': 'Montagem Injuriosum Retines (Slowed)',
  'album_release_date': '2024-08-23',
  'album_total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/1R1KJCX1oc3xqSbABo2Wpn'},
 {'album_id': '2bqWrlHmNh4M41xOr0p7iN',
  'album_name': 'Funk Secreto (Ultra Slowed)',
  'album_release_date': '2024-09-09',
  'album_total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/2bqWrlHmNh4M41xOr0p7iN'},
 {'album_id': '3HEJNpi4OtYpYQlGy2anVB',
  'album_name': 'void',
  'album_release_date': '2024-08-23',
  'album_total_tracks': 3,
  'album_url': 'https://open.spotify.com/album/3HEJNpi4OtYpYQlGy2anVB'},
 {'album_id': '5jXbkZ8fgtvq5OufR9LJz4',
  'album_name': 'BLUE HORIZON FUNK',
  'album_release_date': '2024-11-25',
  'album_total_tracks': 5,
  'album_url': 'https://open.spotify.com/album/5jXbkZ8fgtvq5OufR9LJz4'},
 {'album_id': '7hNzImuUou9dBftesPXcAt',
  'album_name': 'BLAH',
  'album_release_date': '2025-02-13',
  'album_total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/7hNzImuUou9dBftesPXcAt'},
 {'album_id': '1Idktx9vdSSkm1yxABycnf',
  'album_name': 'DON`T STOP',
  'album_release_date': '2024-04-19',
  'album_total_tracks': 5,
  'album_url': 'https://open.spotify.com/album/1Idktx9vdSSkm1yxABycnf'},
 {'album_id': '3xCc8FxQsm6AE7ZWJ7h5sx',
  'album_name': 'SLAY!',
  'album_release_date': '2024-03-15',
  'album_total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/3xCc8FxQsm6AE7ZWJ7h5sx'},
 {'album_id': '5eEfzNcFaXPsBXJzkPiD3S',
  'album_name': 'Beeper Funk (Slowed)',
  'album_release_date': '2024-08-09',
  'album_total_tracks': 2,
  'album_url': 'https://open.spotify.com/album/5eEfzNcFaXPsBXJzkPiD3S'},
 {'album_id': '6PZBt4XZvd1ElHAHG31J1j',
  'album_name': 'FUNK DO BALKAN',
  'album_release_date': '2024-10-18',
  'album_total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/6PZBt4XZvd1ElHAHG31J1j'},
 {'album_id': '05EQpLFKhJ1m4YElm4zDHr',
  'album_name': 'Ela Vira Mortal',
  'album_release_date': '2022-08-05',
  'album_total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/05EQpLFKhJ1m4YElm4zDHr'},
 {'album_id': '5Ide1hRSwzUYUnTQhq6CBv',
  'album_name': 'Death Is No More',
  'album_release_date': '2021-01-25',
  'album_total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/5Ide1hRSwzUYUnTQhq6CBv'},
 {'album_id': '7Bc7xEWvkW01bvq5jAhCQS',
  'album_name': 'YUM YUM',
  'album_release_date': '2023-06-23',
  'album_total_tracks': 3,
  'album_url': 'https://open.spotify.com/album/7Bc7xEWvkW01bvq5jAhCQS'},
 {'album_id': '2DNOGCn0szoh9f3rAnhF7b',
  'album_name': 'BAD PARENTING FUNK',
  'album_release_date': '2024-10-22',
  'album_total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/2DNOGCn0szoh9f3rAnhF7b'},
 {'album_id': '4ibsk1iPM7xDpJkNXREmsl',
  'album_name': 'MANDA BALA',
  'album_release_date': '2023-12-08',
  'album_total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/4ibsk1iPM7xDpJkNXREmsl'},
 {'album_id': '7lolzbhq4moSJPfFpdosl5',
  'album_name': 'RISADA CHUCK 01',
  'album_release_date': '2024-08-26',
  'album_total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/7lolzbhq4moSJPfFpdosl5'},
 {'album_id': '5J00ADHG1jlJiLjQDPURVh',
  'album_name': 'ICEWHORE!',
  'album_release_date': '2023-03-24',
  'album_total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/5J00ADHG1jlJiLjQDPURVh'},
 {'album_id': '28N1pcdMLhrEajfJKkBkl1',
  'album_name': 'MONTAGEM DIAMANTE ROSA',
  'album_release_date': '2024-01-09',
  'album_total_tracks': 2,
  'album_url': 'https://open.spotify.com/album/28N1pcdMLhrEajfJKkBkl1'},
 {'album_id': '7DGsEVuwdKBKrzDx8fzEKn',
  'album_name': 'MTG - VINGANÇA',
  'album_release_date': '2024-01-26',
  'album_total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/7DGsEVuwdKBKrzDx8fzEKn'},
 {'album_id': '6h4Lw0QisEuuAwmnMQvbse',
  'album_name': 'VAPO NO SETOR',
  'album_release_date': '2024-08-13',
  'album_total_tracks': 5,
  'album_url': 'https://open.spotify.com/album/6h4Lw0QisEuuAwmnMQvbse'},
 {'album_id': '3D2j7JQjj9Kjc8sOfikmV6',
  'album_name': 'Montagem Melodia Explosiva',
  'album_release_date': '2024-09-06',
  'album_total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/3D2j7JQjj9Kjc8sOfikmV6'},
 {'album_id': '43DSGSYCywacjEkdeSv4DC',
  'album_name': 'MASHA ULTRAFUNK',
  'album_release_date': '2024-03-07',
  'album_total_tracks': 3,
  'album_url': 'https://open.spotify.com/album/43DSGSYCywacjEkdeSv4DC'},
 {'album_id': '6dRJ8zaG9oTGrwpfu0Itld',
  'album_name': 'z-beta 2',
  'album_release_date': '2025-01-03',
  'album_total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/6dRJ8zaG9oTGrwpfu0Itld'},
 {'album_id': '4yUHDMHDEl6Th3jPimciMz',
  'album_name': 'MY TYPE',
  'album_release_date': '2025-01-03',
  'album_total_tracks': 5,
  'album_url': 'https://open.spotify.com/album/4yUHDMHDEl6Th3jPimciMz'},
 {'album_id': '0yr5YRR7l813mmHITxmFWa',
  'album_name': 'BLOODY!',
  'album_release_date': '2024-08-27',
  'album_total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/0yr5YRR7l813mmHITxmFWa'},
 {'album_id': '6OCivCvAUhsjgqn4EJXH87',
  'album_name': 'freedom from self',
  'album_release_date': '2024-09-16',
  'album_total_tracks': 8,
  'album_url': 'https://open.spotify.com/album/6OCivCvAUhsjgqn4EJXH87'},
 {'album_id': '572YC1K4uc7PjFqb6xaICD',
  'album_name': 'BOUNCE FUNK (Slowed)',
  'album_release_date': '2025-02-15',
  'album_total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/572YC1K4uc7PjFqb6xaICD'},
 {'album_id': '5qaY84OJqYT635rMGeWBzJ',
  'album_name': 'CUTE DEPRESSED',
  'album_release_date': '2024-02-02',
  'album_total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/5qaY84OJqYT635rMGeWBzJ'},
 {'album_id': '3Aw43kkDlLE5ZXwQPGHWgO',
  'album_name': 'MONTAGEM LADRAO',
  'album_release_date': '2025-02-05',
  'album_total_tracks': 5,
  'album_url': 'https://open.spotify.com/album/3Aw43kkDlLE5ZXwQPGHWgO'},
 {'album_id': '1fsqVvld64Nym3Byfl6ekY',
  'album_name': 'VOLKSWAGEN FUNK',
  'album_release_date': '2025-01-24',
  'album_total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/1fsqVvld64Nym3Byfl6ekY'},
 {'album_id': '0TwAp1jAUFp1PQtdDlDDW3',
  'album_name': 'GHOST!',
  'album_release_date': '2022-12-02',
  'album_total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/0TwAp1jAUFp1PQtdDlDDW3'},
 {'album_id': '0JQT0alFPE0pKxgiLfhwYz',
  'album_name': 'Montagem sombra estelar 1.0',
  'album_release_date': '2024-11-30',
  'album_total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/0JQT0alFPE0pKxgiLfhwYz'},
 {'album_id': '6mjnYcgnUPMXZpadY3ctr1',
  'album_name': 'Scopin',
  'album_release_date': '2022-04-08',
  'album_total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/6mjnYcgnUPMXZpadY3ctr1'},
 {'album_id': '1l8if9zQ8F0MEHVWYrMREe',
  'album_name': 'Montagem Mysterious Game',
  'album_release_date': '2023-12-01',
  'album_total_tracks': 3,
  'album_url': 'https://open.spotify.com/album/1l8if9zQ8F0MEHVWYrMREe'},
 {'album_id': '6s28IiIJ7ElbJfTPn03D6Y',
  'album_name': 'THOMAS',
  'album_release_date': '2024-04-12',
  'album_total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/6s28IiIJ7ElbJfTPn03D6Y'},
 {'album_id': '4F2WvpcBhSzlbn3WIITz2B',
  'album_name': 'MAZKO',
  'album_release_date': '2024-10-25',
  'album_total_tracks': 3,
  'album_url': 'https://open.spotify.com/album/4F2WvpcBhSzlbn3WIITz2B'},
 {'album_id': '5YHGz0NvgBlhKefmyhP9zO',
  'album_name': 'Automotivo Bibi Fogosa',
  'album_release_date': '2023-11-10',
  'album_total_tracks': 1,
  'album_url': 'https://open.spotify.com/album/5YHGz0NvgBlhKefmyhP9zO'},
 {'album_id': '4KfNJxpu5wfMuGktR9l9LB',
  'album_name': 'CANTO DE LUNA',
  'album_release_date': '2025-05-16',
  'album_total_tracks': 5,
  'album_url': 'https://open.spotify.com/album/4KfNJxpu5wfMuGktR9l9LB'},
 {'album_id': '17Q5BWWS8c59puiKKg2fRO',
  'album_name': 'JOGO MORTO',
  'album_release_date': '2024-11-08',
  'album_total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/17Q5BWWS8c59puiKKg2fRO'},
 {'album_id': '3StJkT99NLpTwoGjzbEqpH',
  'album_name': 'CLIMA LINDO',
  'album_release_date': '2025-06-06',
  'album_total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/3StJkT99NLpTwoGjzbEqpH'},
 {'album_id': '1ytbKNSOn7FALPHrmOqAdN',
  'album_name': 'MONTAGEM ALUCINANTE',
  'album_release_date': '2025-04-01',
  'album_total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/1ytbKNSOn7FALPHrmOqAdN'},
 {'album_id': '2UPwhike9Qp0u3p0OaUzcP',
  'album_name': 'MONTAGEM VOZES TALENTINHO',
  'album_release_date': '2025-08-08',
  'album_total_tracks': 3,
  'album_url': 'https://open.spotify.com/album/2UPwhike9Qp0u3p0OaUzcP'},
 {'album_id': '2b5kmUGgnWXyh4Y0ohWW2b',
  'album_name': 'GOZALO',
  'album_release_date': '2025-09-26',
  'album_total_tracks': 4,
  'album_url': 'https://open.spotify.com/album/2b5kmUGgnWXyh4Y0ohWW2b'}]

In [ ]:
data['items'][0]['track'].keys()

dict_keys(['preview_url', 'available_markets', 'explicit', 'type', 'episode', 'track', 'album', 'artists', 'disc_number', 'track_number', 'duration_ms', 'external_ids', 'external_urls', 'href', 'id', 'name', 'popularity', 'uri', 'is_local'])

In [85]:
data['items'][0]['track']['artists']

[{'external_urls': {'spotify': 'https://open.spotify.com/artist/5SCDfg1YoEfI5gFtXqEWah'},
  'href': 'https://api.spotify.com/v1/artists/5SCDfg1YoEfI5gFtXqEWah',
  'id': '5SCDfg1YoEfI5gFtXqEWah',
  'name': 'ATLXS',
  'type': 'artist',
  'uri': 'spotify:artist:5SCDfg1YoEfI5gFtXqEWah'}]

In [87]:
data['items'][0]['track']['artists'][0]['id']

'5SCDfg1YoEfI5gFtXqEWah'

In [92]:
data['items'][1]['track']['artists']

[{'external_urls': {'spotify': 'https://open.spotify.com/artist/6hB4Px9Gm2FjAB30PXsv8K'},
  'href': 'https://api.spotify.com/v1/artists/6hB4Px9Gm2FjAB30PXsv8K',
  'id': '6hB4Px9Gm2FjAB30PXsv8K',
  'name': 'cape',
  'type': 'artist',
  'uri': 'spotify:artist:6hB4Px9Gm2FjAB30PXsv8K'},
 {'external_urls': {'spotify': 'https://open.spotify.com/artist/62vwt2P3iBw4NwHdDZb27q'},
  'href': 'https://api.spotify.com/v1/artists/62vwt2P3iBw4NwHdDZb27q',
  'id': '62vwt2P3iBw4NwHdDZb27q',
  'name': 'JXNDRO',
  'type': 'artist',
  'uri': 'spotify:artist:62vwt2P3iBw4NwHdDZb27q'},
 {'external_urls': {'spotify': 'https://open.spotify.com/artist/6s4LSwgbzTAfnN6OUfegJB'},
  'href': 'https://api.spotify.com/v1/artists/6s4LSwgbzTAfnN6OUfegJB',
  'id': '6s4LSwgbzTAfnN6OUfegJB',
  'name': 'Sayfalse',
  'type': 'artist',
  'uri': 'spotify:artist:6s4LSwgbzTAfnN6OUfegJB'}]

In [94]:
for row in data['items']:
    for key, value in row.items():
        if key == 'track':
            print(value['artists'])

[{'external_urls': {'spotify': 'https://open.spotify.com/artist/5SCDfg1YoEfI5gFtXqEWah'}, 'href': 'https://api.spotify.com/v1/artists/5SCDfg1YoEfI5gFtXqEWah', 'id': '5SCDfg1YoEfI5gFtXqEWah', 'name': 'ATLXS', 'type': 'artist', 'uri': 'spotify:artist:5SCDfg1YoEfI5gFtXqEWah'}]
[{'external_urls': {'spotify': 'https://open.spotify.com/artist/6hB4Px9Gm2FjAB30PXsv8K'}, 'href': 'https://api.spotify.com/v1/artists/6hB4Px9Gm2FjAB30PXsv8K', 'id': '6hB4Px9Gm2FjAB30PXsv8K', 'name': 'cape', 'type': 'artist', 'uri': 'spotify:artist:6hB4Px9Gm2FjAB30PXsv8K'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/62vwt2P3iBw4NwHdDZb27q'}, 'href': 'https://api.spotify.com/v1/artists/62vwt2P3iBw4NwHdDZb27q', 'id': '62vwt2P3iBw4NwHdDZb27q', 'name': 'JXNDRO', 'type': 'artist', 'uri': 'spotify:artist:62vwt2P3iBw4NwHdDZb27q'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/6s4LSwgbzTAfnN6OUfegJB'}, 'href': 'https://api.spotify.com/v1/artists/6s4LSwgbzTAfnN6OUfegJB', 'id': '6s4LSwgbzTAfnN6OUfegJB', 'name': 'Sayfalse', 'type': 'artist', 'uri': 'spotify:artist:6s4LSwgbzTAfnN6OUfegJB'}]
[{'external_urls': {'spotify': 'https://open.spotify.com/artist/5tIkxADHN80ca0K6HCpWIt'}, 'href': 'https://api.spotify.com/v1/artists/5tIkxADHN80ca0K6HCpWIt', 'id': '5tIkxADHN80ca0K6HCpWIt', 'name': 'ZXKAI', 'type': 'artist', 'uri': 'spotify:artist:5tIkxADHN80ca0K6HCpWIt'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/1M02J1PLobtQYok93DEvVa'}, 'href': 'https://api.spotify.com/v1/artists/1M02J1PLobtQYok93DEvVa', 'id': '1M02J1PLobtQYok93DEvVa', 'name': 'slxughter', 'type': 'artist', 'uri': 'spotify:artist:1M02J1PLobtQYok93DEvVa'}]
[{'external_urls': {'spotify': 'https://open.spotify.com/artist/1RklNDIiYVZ3dYdEUnB0cS'}, 'href': 'https://api.spotify.com/v1/artists/1RklNDIiYVZ3dYdEUnB0cS', 'id': '1RklNDIiYVZ3dYdEUnB0cS', 'name': 'ANDROMEDA', 'type': 'artist', 'uri': 'spotify:artist:1RklNDIiYVZ3dYdEUnB0cS'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/51K0b3lRd87cKX02hU26we'}, 'href': 'https://api.spotify.com/v1/artists/51K0b3lRd87cKX02hU26we', 'id': '51K0b3lRd87cKX02hU26we', 'name': 'elysian.', 'type': 'artist', 'uri': 'spotify:artist:51K0b3lRd87cKX02hU26we'}]
[{'external_urls': {'spotify': 'https://open.spotify.com/artist/1yevH7mkPMXeSTnA9SwHvq'}, 'href': 'https://api.spotify.com/v1/artists/1yevH7mkPMXeSTnA9SwHvq', 'id': '1yevH7mkPMXeSTnA9SwHvq', 'name': 'SEKIMANE', 'type': 'artist', 'uri': 'spotify:artist:1yevH7mkPMXeSTnA9SwHvq'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/5dDNNq04RjKXFOADdHd6VX'}, 'href': 'https://api.spotify.com/v1/artists/5dDNNq04RjKXFOADdHd6VX', 'id': '5dDNNq04RjKXFOADdHd6VX', 'name': 'Scythermane', 'type': 'artist', 'uri': 'spotify:artist:5dDNNq04RjKXFOADdHd6VX'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/7lAaAGxYxk2GH8cMbTEwAL'}, 'href': 'https://api.spotify.com/v1/artists/7lAaAGxYxk2GH8cMbTEwAL', 'id': '7lAaAGxYxk2GH8cMbTEwAL', 'name': 'NXGHT!', 'type': 'artist', 'uri': 'spotify:artist:7lAaAGxYxk2GH8cMbTEwAL'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/26COCLBHY0CCqCbSlIKWee'}, 'href': 'https://api.spotify.com/v1/artists/26COCLBHY0CCqCbSlIKWee', 'id': '26COCLBHY0CCqCbSlIKWee', 'name': 'DJ DYLANFK', 'type': 'artist', 'uri': 'spotify:artist:26COCLBHY0CCqCbSlIKWee'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/23zmS2d4hkOtvBlJ6T5dqM'}, 'href': 'https://api.spotify.com/v1/artists/23zmS2d4hkOtvBlJ6T5dqM', 'id': '23zmS2d4hkOtvBlJ6T5dqM', 'name': 'KGJ', 'type': 'artist', 'uri': 'spotify:artist:23zmS2d4hkOtvBlJ6T5dqM'}]
[{'external_urls': {'spotify': 'https://open.spotify.com/artist/5dDNNq04RjKXFOADdHd6VX'}, 'href': 'https://api.spotify.com/v1/artists/5dDNNq04RjKXFOADdHd6VX', 'id': '5dDNNq04RjKXFOADdHd6VX', 'name': 'Scythermane', 'type': 'artist', 'uri': 'spotify:artist:5dDNNq04RjKXFOADdHd6VX'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/7lAaAGxYxk2GH8cMbTEwAL'}, 'href': 'https://api.spotify.com/v1/artists/7lAaAGxYxk2GH8cMbTEwAL', 'id': '7lAaAGxYxk2GH8cMbTEwAL', 'name': 'NXGHT!', 'type': 'artist', 'uri': 'spotify:artist:7lAaAGxYxk2GH8cMbTEwAL'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/14hsjenLEdvafsGkk2CEiF'}, 'href': 'https://api.spotify.com/v1/artists/14hsjenLEdvafsGkk2CEiF', 'id': '14hsjenLEdvafsGkk2CEiF', 'name': 'MC Fabinho da Osk', 'type': 'artist', 'uri': 'spotify:artist:14hsjenLEdvafsGkk2CEiF'}]
[{'external_urls': {'spotify': 'https://open.spotify.com/artist/3SENePgknpJt3DvLK2JAfZ'}, 'href': 'https://api.spotify.com/v1/artists/3SENePgknpJt3DvLK2JAfZ', 'id': '3SENePgknpJt3DvLK2JAfZ', 'name': 'KHAOS', 'type': 'artist', 'uri': 'spotify:artist:3SENePgknpJt3DvLK2JAfZ'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/2q5vFLZus8uaVSzmIwH4Tz'}, 'href': 'https://api.spotify.com/v1/artists/2q5vFLZus8uaVSzmIwH4Tz', 'id': '2q5vFLZus8uaVSzmIwH4Tz', 'name': 'Jmilton', 'type': 'artist', 'uri': 'spotify:artist:2q5vFLZus8uaVSzmIwH4Tz'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/1P2tOPRmSa1XzEdtIEYA9W'}, 'href': 'https://api.spotify.com/v1/artists/1P2tOPRmSa1XzEdtIEYA9W', 'id': '1P2tOPRmSa1XzEdtIEYA9W', 'name': 'Mc Jajá', 'type': 'artist', 'uri': 'spotify:artist:1P2tOPRmSa1XzEdtIEYA9W'}]
[{'external_urls': {'spotify': 'https://open.spotify.com/artist/1kd6WqngBvP0Vthu1sGI0j'}, 'href': 'https://api.spotify.com/v1/artists/1kd6WqngBvP0Vthu1sGI0j', 'id': '1kd6WqngBvP0Vthu1sGI0j', 'name': 'Nakama', 'type': 'artist', 'uri': 'spotify:artist:1kd6WqngBvP0Vthu1sGI0j'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/2Q3xviVw2VXFRXtsF2gpR1'}, 'href': 'https://api.spotify.com/v1/artists/2Q3xviVw2VXFRXtsF2gpR1', 'id': '2Q3xviVw2VXFRXtsF2gpR1', 'name': 'ΣP', 'type': 'artist', 'uri': 'spotify:artist:2Q3xviVw2VXFRXtsF2gpR1'}]
[{'external_urls': {'spotify': 'https://open.spotify.com/artist/6s4LSwgbzTAfnN6OUfegJB'}, 'href': 'https://api.spotify.com/v1/artists/6s4LSwgbzTAfnN6OUfegJB', 'id': '6s4LSwgbzTAfnN6OUfegJB', 'name': 'Sayfalse', 'type': 'artist', 'uri': 'spotify:artist:6s4LSwgbzTAfnN6OUfegJB'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/2LWzzk1DrqcGB0h3ezY8qo'}, 'href': 'https://api.spotify.com/v1/artists/2LWzzk1DrqcGB0h3ezY8qo', 'id': '2LWzzk1DrqcGB0h3ezY8qo', 'name': 'SNXP', 'type': 'artist', 'uri': 'spotify:artist:2LWzzk1DrqcGB0h3ezY8qo'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/6HwL7jLVz0vywuLyHq3ozr'}, 'href': 'https://api.spotify.com/v1/artists/6HwL7jLVz0vywuLyHq3ozr', 'id': '6HwL7jLVz0vywuLyHq3ozr', 'name': 'ßino', 'type': 'artist', 'uri': 'spotify:artist:6HwL7jLVz0vywuLyHq3ozr'}]
[{'external_urls': {'spotify': 'https://open.spotify.com/artist/5bePP411ITzZyWf1QZ2SX4'}, 'href': 'https://api.spotify.com/v1/artists/5bePP411ITzZyWf1QZ2SX4', 'id': '5bePP411ITzZyWf1QZ2SX4', 'name': 'Flame Runner', 'type': 'artist', 'uri': 'spotify:artist:5bePP411ITzZyWf1QZ2SX4'}]
[{'external_urls': {'spotify': 'https://open.spotify.com/artist/3g0UoyvaTaHUrfpHiRqsD1'}, 'href': 'https://api.spotify.com/v1/artists/3g0UoyvaTaHUrfpHiRqsD1', 'id': '3g0UoyvaTaHUrfpHiRqsD1', 'name': 'Nateki', 'type': 'artist', 'uri': 'spotify:artist:3g0UoyvaTaHUrfpHiRqsD1'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/5dDNNq04RjKXFOADdHd6VX'}, 'href': 'https://api.spotify.com/v1/artists/5dDNNq04RjKXFOADdHd6VX', 'id': '5dDNNq04RjKXFOADdHd6VX', 'name': 'Scythermane', 'type': 'artist', 'uri': 'spotify:artist:5dDNNq04RjKXFOADdHd6VX'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/10mKIVPFtg42JIvttHQrzr'}, 'href': 'https://api.spotify.com/v1/artists/10mKIVPFtg42JIvttHQrzr', 'id': '10mKIVPFtg42JIvttHQrzr', 'name': 'MC MAYAH', 'type': 'artist', 'uri': 'spotify:artist:10mKIVPFtg42JIvttHQrzr'}]
[{'external_urls': {'spotify': 'https://open.spotify.com/artist/2q5vFLZus8uaVSzmIwH4Tz'}, 'href': 'https://api.spotify.com/v1/artists/2q5vFLZus8uaVSzmIwH4Tz', 'id': '2q5vFLZus8uaVSzmIwH4Tz', 'name': 'Jmilton', 'type': 'artist', 'uri': 'spotify:artist:2q5vFLZus8uaVSzmIwH4Tz'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/67PBOFpTBFaNkhz5IouBwi'}, 'href': 'https://api.spotify.com/v1/artists/67PBOFpTBFaNkhz5IouBwi', 'id': '67PBOFpTBFaNkhz5IouBwi', 'name': 'MC Xangai', 'type': 'artist', 'uri': 'spotify:artist:67PBOFpTBFaNkhz5IouBwi'}]
[{'external_urls': {'spotify': 'https://open.spotify.com/artist/1Fl1fc7bZfRVUCffh9Uudx'}, 'href': 'https://api.spotify.com/v1/artists/1Fl1fc7bZfRVUCffh9Uudx', 'id': '1Fl1fc7bZfRVUCffh9Uudx', 'name': 'sma$her', 'type': 'artist', 'uri': 'spotify:artist:1Fl1fc7bZfRVUCffh9Uudx'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/7kk9ucvRJim0NMM89Lml2Y'}, 'href': 'https://api.spotify.com/v1/artists/7kk9ucvRJim0NMM89Lml2Y', 'id': '7kk9ucvRJim0NMM89Lml2Y', 'name': 'MXZI', 'type': 'artist', 'uri': 'spotify:artist:7kk9ucvRJim0NMM89Lml2Y'}]
[{'external_urls': {'spotify': 'https://open.spotify.com/artist/7kk9ucvRJim0NMM89Lml2Y'}, 'href': 'https://api.spotify.com/v1/artists/7kk9ucvRJim0NMM89Lml2Y', 'id': '7kk9ucvRJim0NMM89Lml2Y', 'name': 'MXZI', 'type': 'artist', 'uri': 'spotify:artist:7kk9ucvRJim0NMM89Lml2Y'}]
[{'external_urls': {'spotify': 'https://open.spotify.com/artist/6s4LSwgbzTAfnN6OUfegJB'}, 'href': 'https://api.spotify.com/v1/artists/6s4LSwgbzTAfnN6OUfegJB', 'id': '6s4LSwgbzTAfnN6OUfegJB', 'name': 'Sayfalse', 'type': 'artist', 'uri': 'spotify:artist:6s4LSwgbzTAfnN6OUfegJB'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/5dDNNq04RjKXFOADdHd6VX'}, 'href': 'https://api.spotify.com/v1/artists/5dDNNq04RjKXFOADdHd6VX', 'id': '5dDNNq04RjKXFOADdHd6VX', 'name': 'Scythermane', 'type': 'artist', 'uri': 'spotify:artist:5dDNNq04RjKXFOADdHd6VX'}]
[{'external_urls': {'spotify': 'https://open.spotify.com/artist/7kk9ucvRJim0NMM89Lml2Y'}, 'href': 'https://api.spotify.com/v1/artists/7kk9ucvRJim0NMM89Lml2Y', 'id': '7kk9ucvRJim0NMM89Lml2Y', 'name': 'MXZI', 'type': 'artist', 'uri': 'spotify:artist:7kk9ucvRJim0NMM89Lml2Y'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/6U0dJxYVB41L8WDZ02Nwuk'}, 'href': 'https://api.spotify.com/v1/artists/6U0dJxYVB41L8WDZ02Nwuk', 'id': '6U0dJxYVB41L8WDZ02Nwuk', 'name': 'Dj Samir', 'type': 'artist', 'uri': 'spotify:artist:6U0dJxYVB41L8WDZ02Nwuk'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/0JGZRsRtFTQ0ZVBq9b2ZEj'}, 'href': 'https://api.spotify.com/v1/artists/0JGZRsRtFTQ0ZVBq9b2ZEj', 'id': '0JGZRsRtFTQ0ZVBq9b2ZEj', 'name': 'DJ Javi26', 'type': 'artist', 'uri': 'spotify:artist:0JGZRsRtFTQ0ZVBq9b2ZEj'}]
[{'external_urls': {'spotify': 'https://open.spotify.com/artist/0exQbKNFd9pLmdIGycwmlf'}, 'href': 'https://api.spotify.com/v1/artists/0exQbKNFd9pLmdIGycwmlf', 'id': '0exQbKNFd9pLmdIGycwmlf', 'name': 'h6itam', 'type': 'artist', 'uri': 'spotify:artist:0exQbKNFd9pLmdIGycwmlf'}]
[{'external_urls': {'spotify': 'https://open.spotify.com/artist/1kd6WqngBvP0Vthu1sGI0j'}, 'href': 'https://api.spotify.com/v1/artists/1kd6WqngBvP0Vthu1sGI0j', 'id': '1kd6WqngBvP0Vthu1sGI0j', 'name': 'Nakama', 'type': 'artist', 'uri': 'spotify:artist:1kd6WqngBvP0Vthu1sGI0j'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/3awueWqdp1OZudPelsEIgx'}, 'href': 'https://api.spotify.com/v1/artists/3awueWqdp1OZudPelsEIgx', 'id': '3awueWqdp1OZudPelsEIgx', 'name': 'Mc Staff', 'type': 'artist', 'uri': 'spotify:artist:3awueWqdp1OZudPelsEIgx'}]
[{'external_urls': {'spotify': 'https://open.spotify.com/artist/7kk9ucvRJim0NMM89Lml2Y'}, 'href': 'https://api.spotify.com/v1/artists/7kk9ucvRJim0NMM89Lml2Y', 'id': '7kk9ucvRJim0NMM89Lml2Y', 'name': 'MXZI', 'type': 'artist', 'uri': 'spotify:artist:7kk9ucvRJim0NMM89Lml2Y'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/55TpSGABb9xsmXHkqbv3ti'}, 'href': 'https://api.spotify.com/v1/artists/55TpSGABb9xsmXHkqbv3ti', 'id': '55TpSGABb9xsmXHkqbv3ti', 'name': 'Rushex', 'type': 'artist', 'uri': 'spotify:artist:55TpSGABb9xsmXHkqbv3ti'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/6gzkhdNfpMIPg91TnzlcCh'}, 'href': 'https://api.spotify.com/v1/artists/6gzkhdNfpMIPg91TnzlcCh', 'id': '6gzkhdNfpMIPg91TnzlcCh', 'name': 'MONTAGEM', 'type': 'artist', 'uri': 'spotify:artist:6gzkhdNfpMIPg91TnzlcCh'}]
[{'external_urls': {'spotify': 'https://open.spotify.com/artist/0jrirfCZkRU3iA2sH9JEko'}, 'href': 'https://api.spotify.com/v1/artists/0jrirfCZkRU3iA2sH9JEko', 'id': '0jrirfCZkRU3iA2sH9JEko', 'name': 'Repsaj', 'type': 'artist', 'uri': 'spotify:artist:0jrirfCZkRU3iA2sH9JEko'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/7kk9ucvRJim0NMM89Lml2Y'}, 'href': 'https://api.spotify.com/v1/artists/7kk9ucvRJim0NMM89Lml2Y', 'id': '7kk9ucvRJim0NMM89Lml2Y', 'name': 'MXZI', 'type': 'artist', 'uri': 'spotify:artist:7kk9ucvRJim0NMM89Lml2Y'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/5SCDfg1YoEfI5gFtXqEWah'}, 'href': 'https://api.spotify.com/v1/artists/5SCDfg1YoEfI5gFtXqEWah', 'id': '5SCDfg1YoEfI5gFtXqEWah', 'name': 'ATLXS', 'type': 'artist', 'uri': 'spotify:artist:5SCDfg1YoEfI5gFtXqEWah'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/34giN3qeTOdgDSJIdtIMdm'}, 'href': 'https://api.spotify.com/v1/artists/34giN3qeTOdgDSJIdtIMdm', 'id': '34giN3qeTOdgDSJIdtIMdm', 'name': 'Mc Jhey', 'type': 'artist', 'uri': 'spotify:artist:34giN3qeTOdgDSJIdtIMdm'}]
[{'external_urls': {'spotify': 'https://open.spotify.com/artist/5bePP411ITzZyWf1QZ2SX4'}, 'href': 'https://api.spotify.com/v1/artists/5bePP411ITzZyWf1QZ2SX4', 'id': '5bePP411ITzZyWf1QZ2SX4', 'name': 'Flame Runner', 'type': 'artist', 'uri': 'spotify:artist:5bePP411ITzZyWf1QZ2SX4'}]
[{'external_urls': {'spotify': 'https://open.spotify.com/artist/7qIgmxSjoXEeifSVDh8nIt'}, 'href': 'https://api.spotify.com/v1/artists/7qIgmxSjoXEeifSVDh8nIt', 'id': '7qIgmxSjoXEeifSVDh8nIt', 'name': 'MXCCREE', 'type': 'artist', 'uri': 'spotify:artist:7qIgmxSjoXEeifSVDh8nIt'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/1dX1zejt24Ojiu0lX4T1ZM'}, 'href': 'https://api.spotify.com/v1/artists/1dX1zejt24Ojiu0lX4T1ZM', 'id': '1dX1zejt24Ojiu0lX4T1ZM', 'name': 'DJ GL3CHEKY', 'type': 'artist', 'uri': 'spotify:artist:1dX1zejt24Ojiu0lX4T1ZM'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/0Vxqvpm9tpZcz6d4egDtjX'}, 'href': 'https://api.spotify.com/v1/artists/0Vxqvpm9tpZcz6d4egDtjX', 'id': '0Vxqvpm9tpZcz6d4egDtjX', 'name': 'MC PR', 'type': 'artist', 'uri': 'spotify:artist:0Vxqvpm9tpZcz6d4egDtjX'}]
[{'external_urls': {'spotify': 'https://open.spotify.com/artist/2vKxv2oKVSEJZ1VmuLUOvY'}, 'href': 'https://api.spotify.com/v1/artists/2vKxv2oKVSEJZ1VmuLUOvY', 'id': '2vKxv2oKVSEJZ1VmuLUOvY', 'name': 'Irokz', 'type': 'artist', 'uri': 'spotify:artist:2vKxv2oKVSEJZ1VmuLUOvY'}]
[{'external_urls': {'spotify': 'https://open.spotify.com/artist/6s4LSwgbzTAfnN6OUfegJB'}, 'href': 'https://api.spotify.com/v1/artists/6s4LSwgbzTAfnN6OUfegJB', 'id': '6s4LSwgbzTAfnN6OUfegJB', 'name': 'Sayfalse', 'type': 'artist', 'uri': 'spotify:artist:6s4LSwgbzTAfnN6OUfegJB'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/02wf6SCDwrs2qTX09X0IRE'}, 'href': 'https://api.spotify.com/v1/artists/02wf6SCDwrs2qTX09X0IRE', 'id': '02wf6SCDwrs2qTX09X0IRE', 'name': "Yb Wasg'ood", 'type': 'artist', 'uri': 'spotify:artist:02wf6SCDwrs2qTX09X0IRE'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/09cKncAQn28NqTUORLMwSR'}, 'href': 'https://api.spotify.com/v1/artists/09cKncAQn28NqTUORLMwSR', 'id': '09cKncAQn28NqTUORLMwSR', 'name': 'Ariis', 'type': 'artist', 'uri': 'spotify:artist:09cKncAQn28NqTUORLMwSR'}]
[{'external_urls': {'spotify': 'https://open.spotify.com/artist/02wf6SCDwrs2qTX09X0IRE'}, 'href': 'https://api.spotify.com/v1/artists/02wf6SCDwrs2qTX09X0IRE', 'id': '02wf6SCDwrs2qTX09X0IRE', 'name': "Yb Wasg'ood", 'type': 'artist', 'uri': 'spotify:artist:02wf6SCDwrs2qTX09X0IRE'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/09cKncAQn28NqTUORLMwSR'}, 'href': 'https://api.spotify.com/v1/artists/09cKncAQn28NqTUORLMwSR', 'id': '09cKncAQn28NqTUORLMwSR', 'name': 'Ariis', 'type': 'artist', 'uri': 'spotify:artist:09cKncAQn28NqTUORLMwSR'}]
[{'external_urls': {'spotify': 'https://open.spotify.com/artist/2nGwC9QG6Hpw4fSDgNpn5n'}, 'href': 'https://api.spotify.com/v1/artists/2nGwC9QG6Hpw4fSDgNpn5n', 'id': '2nGwC9QG6Hpw4fSDgNpn5n', 'name': 'JXM', 'type': 'artist', 'uri': 'spotify:artist:2nGwC9QG6Hpw4fSDgNpn5n'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/4DWPOsGWbW7sBHb1UuBvWs'}, 'href': 'https://api.spotify.com/v1/artists/4DWPOsGWbW7sBHb1UuBvWs', 'id': '4DWPOsGWbW7sBHb1UuBvWs', 'name': 'Polaris', 'type': 'artist', 'uri': 'spotify:artist:4DWPOsGWbW7sBHb1UuBvWs'}]
[{'external_urls': {'spotify': 'https://open.spotify.com/artist/4nl0CCx6PpEOOr2Z2ThPdp'}, 'href': 'https://api.spotify.com/v1/artists/4nl0CCx6PpEOOr2Z2ThPdp', 'id': '4nl0CCx6PpEOOr2Z2ThPdp', 'name': 'xxanteria', 'type': 'artist', 'uri': 'spotify:artist:4nl0CCx6PpEOOr2Z2ThPdp'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/6JjQbtAO09K7qBEW2pdX5s'}, 'href': 'https://api.spotify.com/v1/artists/6JjQbtAO09K7qBEW2pdX5s', 'id': '6JjQbtAO09K7qBEW2pdX5s', 'name': 'isq', 'type': 'artist', 'uri': 'spotify:artist:6JjQbtAO09K7qBEW2pdX5s'}]
[{'external_urls': {'spotify': 'https://open.spotify.com/artist/09cKncAQn28NqTUORLMwSR'}, 'href': 'https://api.spotify.com/v1/artists/09cKncAQn28NqTUORLMwSR', 'id': '09cKncAQn28NqTUORLMwSR', 'name': 'Ariis', 'type': 'artist', 'uri': 'spotify:artist:09cKncAQn28NqTUORLMwSR'}]
[{'external_urls': {'spotify': 'https://open.spotify.com/artist/2vPnS0IpayC2RVFuQA08R4'}, 'href': 'https://api.spotify.com/v1/artists/2vPnS0IpayC2RVFuQA08R4', 'id': '2vPnS0IpayC2RVFuQA08R4', 'name': '2KE', 'type': 'artist', 'uri': 'spotify:artist:2vPnS0IpayC2RVFuQA08R4'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/4jM6R2LK78dVTqHVUoA4li'}, 'href': 'https://api.spotify.com/v1/artists/4jM6R2LK78dVTqHVUoA4li', 'id': '4jM6R2LK78dVTqHVUoA4li', 'name': '808iuli', 'type': 'artist', 'uri': 'spotify:artist:4jM6R2LK78dVTqHVUoA4li'}]
[{'external_urls': {'spotify': 'https://open.spotify.com/artist/1Sdc6ySbIvzO0X9vbyHzWm'}, 'href': 'https://api.spotify.com/v1/artists/1Sdc6ySbIvzO0X9vbyHzWm', 'id': '1Sdc6ySbIvzO0X9vbyHzWm', 'name': 'Ogryzek', 'type': 'artist', 'uri': 'spotify:artist:1Sdc6ySbIvzO0X9vbyHzWm'}]
[{'external_urls': {'spotify': 'https://open.spotify.com/artist/5tvPbCrx8LMaL9Zby5e7c2'}, 'href': 'https://api.spotify.com/v1/artists/5tvPbCrx8LMaL9Zby5e7c2', 'id': '5tvPbCrx8LMaL9Zby5e7c2', 'name': 'fennecxx', 'type': 'artist', 'uri': 'spotify:artist:5tvPbCrx8LMaL9Zby5e7c2'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/7FqHcUwnhxJZAgS3I6GFFL'}, 'href': 'https://api.spotify.com/v1/artists/7FqHcUwnhxJZAgS3I6GFFL', 'id': '7FqHcUwnhxJZAgS3I6GFFL', 'name': 'DJ ALEX', 'type': 'artist', 'uri': 'spotify:artist:7FqHcUwnhxJZAgS3I6GFFL'}]
[{'external_urls': {'spotify': 'https://open.spotify.com/artist/0oGN0s7dqyWbR41yMsNs0R'}, 'href': 'https://api.spotify.com/v1/artists/0oGN0s7dqyWbR41yMsNs0R', 'id': '0oGN0s7dqyWbR41yMsNs0R', 'name': 'princce', 'type': 'artist', 'uri': 'spotify:artist:0oGN0s7dqyWbR41yMsNs0R'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/2YXKTfoEjKVzCNI0J6rHbQ'}, 'href': 'https://api.spotify.com/v1/artists/2YXKTfoEjKVzCNI0J6rHbQ', 'id': '2YXKTfoEjKVzCNI0J6rHbQ', 'name': 'FR3ST', 'type': 'artist', 'uri': 'spotify:artist:2YXKTfoEjKVzCNI0J6rHbQ'}]
[{'external_urls': {'spotify': 'https://open.spotify.com/artist/1Sdc6ySbIvzO0X9vbyHzWm'}, 'href': 'https://api.spotify.com/v1/artists/1Sdc6ySbIvzO0X9vbyHzWm', 'id': '1Sdc6ySbIvzO0X9vbyHzWm', 'name': 'Ogryzek', 'type': 'artist', 'uri': 'spotify:artist:1Sdc6ySbIvzO0X9vbyHzWm'}]
[{'external_urls': {'spotify': 'https://open.spotify.com/artist/3qycxIGAHj1KyoAQ6PGCO6'}, 'href': 'https://api.spotify.com/v1/artists/3qycxIGAHj1KyoAQ6PGCO6', 'id': '3qycxIGAHj1KyoAQ6PGCO6', 'name': 'Seek', 'type': 'artist', 'uri': 'spotify:artist:3qycxIGAHj1KyoAQ6PGCO6'}]

In [95]:
for row in data['items']:
    for key, value in row.items():
        if key == 'track':
            for artist in value['artists']:
                print(artist)

{'external_urls': {'spotify': 'https://open.spotify.com/artist/5SCDfg1YoEfI5gFtXqEWah'}, 'href': 'https://api.spotify.com/v1/artists/5SCDfg1YoEfI5gFtXqEWah', 'id': '5SCDfg1YoEfI5gFtXqEWah', 'name': 'ATLXS', 'type': 'artist', 'uri': 'spotify:artist:5SCDfg1YoEfI5gFtXqEWah'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/6hB4Px9Gm2FjAB30PXsv8K'}, 'href': 'https://api.spotify.com/v1/artists/6hB4Px9Gm2FjAB30PXsv8K', 'id': '6hB4Px9Gm2FjAB30PXsv8K', 'name': 'cape', 'type': 'artist', 'uri': 'spotify:artist:6hB4Px9Gm2FjAB30PXsv8K'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/62vwt2P3iBw4NwHdDZb27q'}, 'href': 'https://api.spotify.com/v1/artists/62vwt2P3iBw4NwHdDZb27q', 'id': '62vwt2P3iBw4NwHdDZb27q', 'name': 'JXNDRO', 'type': 'artist', 'uri': 'spotify:artist:62vwt2P3iBw4NwHdDZb27q'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/6s4LSwgbzTAfnN6OUfegJB'}, 'href': 'https://api.spotify.com/v1/artists/6s4LSwgbzTAfnN6OUfegJB', 'id': '6s4LSwgbzTAfnN6OUfegJB', 'name': 'Sayfalse', 'type': 'artist', 'uri': 'spotify:artist:6s4LSwgbzTAfnN6OUfegJB'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/5tIkxADHN80ca0K6HCpWIt'}, 'href': 'https://api.spotify.com/v1/artists/5tIkxADHN80ca0K6HCpWIt', 'id': '5tIkxADHN80ca0K6HCpWIt', 'name': 'ZXKAI', 'type': 'artist', 'uri': 'spotify:artist:5tIkxADHN80ca0K6HCpWIt'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/1M02J1PLobtQYok93DEvVa'}, 'href': 'https://api.spotify.com/v1/artists/1M02J1PLobtQYok93DEvVa', 'id': '1M02J1PLobtQYok93DEvVa', 'name': 'slxughter', 'type': 'artist', 'uri': 'spotify:artist:1M02J1PLobtQYok93DEvVa'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/1RklNDIiYVZ3dYdEUnB0cS'}, 'href': 'https://api.spotify.com/v1/artists/1RklNDIiYVZ3dYdEUnB0cS', 'id': '1RklNDIiYVZ3dYdEUnB0cS', 'name': 'ANDROMEDA', 'type': 'artist', 'uri': 'spotify:artist:1RklNDIiYVZ3dYdEUnB0cS'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/51K0b3lRd87cKX02hU26we'}, 'href': 'https://api.spotify.com/v1/artists/51K0b3lRd87cKX02hU26we', 'id': '51K0b3lRd87cKX02hU26we', 'name': 'elysian.', 'type': 'artist', 'uri': 'spotify:artist:51K0b3lRd87cKX02hU26we'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/1yevH7mkPMXeSTnA9SwHvq'}, 'href': 'https://api.spotify.com/v1/artists/1yevH7mkPMXeSTnA9SwHvq', 'id': '1yevH7mkPMXeSTnA9SwHvq', 'name': 'SEKIMANE', 'type': 'artist', 'uri': 'spotify:artist:1yevH7mkPMXeSTnA9SwHvq'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/5dDNNq04RjKXFOADdHd6VX'}, 'href': 'https://api.spotify.com/v1/artists/5dDNNq04RjKXFOADdHd6VX', 'id': '5dDNNq04RjKXFOADdHd6VX', 'name': 'Scythermane', 'type': 'artist', 'uri': 'spotify:artist:5dDNNq04RjKXFOADdHd6VX'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/7lAaAGxYxk2GH8cMbTEwAL'}, 'href': 'https://api.spotify.com/v1/artists/7lAaAGxYxk2GH8cMbTEwAL', 'id': '7lAaAGxYxk2GH8cMbTEwAL', 'name': 'NXGHT!', 'type': 'artist', 'uri': 'spotify:artist:7lAaAGxYxk2GH8cMbTEwAL'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/26COCLBHY0CCqCbSlIKWee'}, 'href': 'https://api.spotify.com/v1/artists/26COCLBHY0CCqCbSlIKWee', 'id': '26COCLBHY0CCqCbSlIKWee', 'name': 'DJ DYLANFK', 'type': 'artist', 'uri': 'spotify:artist:26COCLBHY0CCqCbSlIKWee'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/23zmS2d4hkOtvBlJ6T5dqM'}, 'href': 'https://api.spotify.com/v1/artists/23zmS2d4hkOtvBlJ6T5dqM', 'id': '23zmS2d4hkOtvBlJ6T5dqM', 'name': 'KGJ', 'type': 'artist', 'uri': 'spotify:artist:23zmS2d4hkOtvBlJ6T5dqM'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/5dDNNq04RjKXFOADdHd6VX'}, 'href': 'https://api.spotify.com/v1/artists/5dDNNq04RjKXFOADdHd6VX', 'id': '5dDNNq04RjKXFOADdHd6VX', 'name': 'Scythermane', 'type': 'artist', 'uri': 'spotify:artist:5dDNNq04RjKXFOADdHd6VX'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/7lAaAGxYxk2GH8cMbTEwAL'}, 'href': 'https://api.spotify.com/v1/artists/7lAaAGxYxk2GH8cMbTEwAL', 'id': '7lAaAGxYxk2GH8cMbTEwAL', 'name': 'NXGHT!', 'type': 'artist', 'uri': 'spotify:artist:7lAaAGxYxk2GH8cMbTEwAL'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/14hsjenLEdvafsGkk2CEiF'}, 'href': 'https://api.spotify.com/v1/artists/14hsjenLEdvafsGkk2CEiF', 'id': '14hsjenLEdvafsGkk2CEiF', 'name': 'MC Fabinho da Osk', 'type': 'artist', 'uri': 'spotify:artist:14hsjenLEdvafsGkk2CEiF'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/3SENePgknpJt3DvLK2JAfZ'}, 'href': 'https://api.spotify.com/v1/artists/3SENePgknpJt3DvLK2JAfZ', 'id': '3SENePgknpJt3DvLK2JAfZ', 'name': 'KHAOS', 'type': 'artist', 'uri': 'spotify:artist:3SENePgknpJt3DvLK2JAfZ'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/2q5vFLZus8uaVSzmIwH4Tz'}, 'href': 'https://api.spotify.com/v1/artists/2q5vFLZus8uaVSzmIwH4Tz', 'id': '2q5vFLZus8uaVSzmIwH4Tz', 'name': 'Jmilton', 'type': 'artist', 'uri': 'spotify:artist:2q5vFLZus8uaVSzmIwH4Tz'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/1P2tOPRmSa1XzEdtIEYA9W'}, 'href': 'https://api.spotify.com/v1/artists/1P2tOPRmSa1XzEdtIEYA9W', 'id': '1P2tOPRmSa1XzEdtIEYA9W', 'name': 'Mc Jajá', 'type': 'artist', 'uri': 'spotify:artist:1P2tOPRmSa1XzEdtIEYA9W'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/1kd6WqngBvP0Vthu1sGI0j'}, 'href': 'https://api.spotify.com/v1/artists/1kd6WqngBvP0Vthu1sGI0j', 'id': '1kd6WqngBvP0Vthu1sGI0j', 'name': 'Nakama', 'type': 'artist', 'uri': 'spotify:artist:1kd6WqngBvP0Vthu1sGI0j'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/2Q3xviVw2VXFRXtsF2gpR1'}, 'href': 'https://api.spotify.com/v1/artists/2Q3xviVw2VXFRXtsF2gpR1', 'id': '2Q3xviVw2VXFRXtsF2gpR1', 'name': 'ΣP', 'type': 'artist', 'uri': 'spotify:artist:2Q3xviVw2VXFRXtsF2gpR1'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/6s4LSwgbzTAfnN6OUfegJB'}, 'href': 'https://api.spotify.com/v1/artists/6s4LSwgbzTAfnN6OUfegJB', 'id': '6s4LSwgbzTAfnN6OUfegJB', 'name': 'Sayfalse', 'type': 'artist', 'uri': 'spotify:artist:6s4LSwgbzTAfnN6OUfegJB'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/2LWzzk1DrqcGB0h3ezY8qo'}, 'href': 'https://api.spotify.com/v1/artists/2LWzzk1DrqcGB0h3ezY8qo', 'id': '2LWzzk1DrqcGB0h3ezY8qo', 'name': 'SNXP', 'type': 'artist', 'uri': 'spotify:artist:2LWzzk1DrqcGB0h3ezY8qo'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/6HwL7jLVz0vywuLyHq3ozr'}, 'href': 'https://api.spotify.com/v1/artists/6HwL7jLVz0vywuLyHq3ozr', 'id': '6HwL7jLVz0vywuLyHq3ozr', 'name': 'ßino', 'type': 'artist', 'uri': 'spotify:artist:6HwL7jLVz0vywuLyHq3ozr'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/5bePP411ITzZyWf1QZ2SX4'}, 'href': 'https://api.spotify.com/v1/artists/5bePP411ITzZyWf1QZ2SX4', 'id': '5bePP411ITzZyWf1QZ2SX4', 'name': 'Flame Runner', 'type': 'artist', 'uri': 'spotify:artist:5bePP411ITzZyWf1QZ2SX4'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/3g0UoyvaTaHUrfpHiRqsD1'}, 'href': 'https://api.spotify.com/v1/artists/3g0UoyvaTaHUrfpHiRqsD1', 'id': '3g0UoyvaTaHUrfpHiRqsD1', 'name': 'Nateki', 'type': 'artist', 'uri': 'spotify:artist:3g0UoyvaTaHUrfpHiRqsD1'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/5dDNNq04RjKXFOADdHd6VX'}, 'href': 'https://api.spotify.com/v1/artists/5dDNNq04RjKXFOADdHd6VX', 'id': '5dDNNq04RjKXFOADdHd6VX', 'name': 'Scythermane', 'type': 'artist', 'uri': 'spotify:artist:5dDNNq04RjKXFOADdHd6VX'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/10mKIVPFtg42JIvttHQrzr'}, 'href': 'https://api.spotify.com/v1/artists/10mKIVPFtg42JIvttHQrzr', 'id': '10mKIVPFtg42JIvttHQrzr', 'name': 'MC MAYAH', 'type': 'artist', 'uri': 'spotify:artist:10mKIVPFtg42JIvttHQrzr'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/2q5vFLZus8uaVSzmIwH4Tz'}, 'href': 'https://api.spotify.com/v1/artists/2q5vFLZus8uaVSzmIwH4Tz', 'id': '2q5vFLZus8uaVSzmIwH4Tz', 'name': 'Jmilton', 'type': 'artist', 'uri': 'spotify:artist:2q5vFLZus8uaVSzmIwH4Tz'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/67PBOFpTBFaNkhz5IouBwi'}, 'href': 'https://api.spotify.com/v1/artists/67PBOFpTBFaNkhz5IouBwi', 'id': '67PBOFpTBFaNkhz5IouBwi', 'name': 'MC Xangai', 'type': 'artist', 'uri': 'spotify:artist:67PBOFpTBFaNkhz5IouBwi'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/1Fl1fc7bZfRVUCffh9Uudx'}, 'href': 'https://api.spotify.com/v1/artists/1Fl1fc7bZfRVUCffh9Uudx', 'id': '1Fl1fc7bZfRVUCffh9Uudx', 'name': 'sma$her', 'type': 'artist', 'uri': 'spotify:artist:1Fl1fc7bZfRVUCffh9Uudx'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/7kk9ucvRJim0NMM89Lml2Y'}, 'href': 'https://api.spotify.com/v1/artists/7kk9ucvRJim0NMM89Lml2Y', 'id': '7kk9ucvRJim0NMM89Lml2Y', 'name': 'MXZI', 'type': 'artist', 'uri': 'spotify:artist:7kk9ucvRJim0NMM89Lml2Y'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/7kk9ucvRJim0NMM89Lml2Y'}, 'href': 'https://api.spotify.com/v1/artists/7kk9ucvRJim0NMM89Lml2Y', 'id': '7kk9ucvRJim0NMM89Lml2Y', 'name': 'MXZI', 'type': 'artist', 'uri': 'spotify:artist:7kk9ucvRJim0NMM89Lml2Y'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/6s4LSwgbzTAfnN6OUfegJB'}, 'href': 'https://api.spotify.com/v1/artists/6s4LSwgbzTAfnN6OUfegJB', 'id': '6s4LSwgbzTAfnN6OUfegJB', 'name': 'Sayfalse', 'type': 'artist', 'uri': 'spotify:artist:6s4LSwgbzTAfnN6OUfegJB'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/5dDNNq04RjKXFOADdHd6VX'}, 'href': 'https://api.spotify.com/v1/artists/5dDNNq04RjKXFOADdHd6VX', 'id': '5dDNNq04RjKXFOADdHd6VX', 'name': 'Scythermane', 'type': 'artist', 'uri': 'spotify:artist:5dDNNq04RjKXFOADdHd6VX'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/7kk9ucvRJim0NMM89Lml2Y'}, 'href': 'https://api.spotify.com/v1/artists/7kk9ucvRJim0NMM89Lml2Y', 'id': '7kk9ucvRJim0NMM89Lml2Y', 'name': 'MXZI', 'type': 'artist', 'uri': 'spotify:artist:7kk9ucvRJim0NMM89Lml2Y'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/6U0dJxYVB41L8WDZ02Nwuk'}, 'href': 'https://api.spotify.com/v1/artists/6U0dJxYVB41L8WDZ02Nwuk', 'id': '6U0dJxYVB41L8WDZ02Nwuk', 'name': 'Dj Samir', 'type': 'artist', 'uri': 'spotify:artist:6U0dJxYVB41L8WDZ02Nwuk'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/0JGZRsRtFTQ0ZVBq9b2ZEj'}, 'href': 'https://api.spotify.com/v1/artists/0JGZRsRtFTQ0ZVBq9b2ZEj', 'id': '0JGZRsRtFTQ0ZVBq9b2ZEj', 'name': 'DJ Javi26', 'type': 'artist', 'uri': 'spotify:artist:0JGZRsRtFTQ0ZVBq9b2ZEj'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/0exQbKNFd9pLmdIGycwmlf'}, 'href': 'https://api.spotify.com/v1/artists/0exQbKNFd9pLmdIGycwmlf', 'id': '0exQbKNFd9pLmdIGycwmlf', 'name': 'h6itam', 'type': 'artist', 'uri': 'spotify:artist:0exQbKNFd9pLmdIGycwmlf'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/1kd6WqngBvP0Vthu1sGI0j'}, 'href': 'https://api.spotify.com/v1/artists/1kd6WqngBvP0Vthu1sGI0j', 'id': '1kd6WqngBvP0Vthu1sGI0j', 'name': 'Nakama', 'type': 'artist', 'uri': 'spotify:artist:1kd6WqngBvP0Vthu1sGI0j'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/3awueWqdp1OZudPelsEIgx'}, 'href': 'https://api.spotify.com/v1/artists/3awueWqdp1OZudPelsEIgx', 'id': '3awueWqdp1OZudPelsEIgx', 'name': 'Mc Staff', 'type': 'artist', 'uri': 'spotify:artist:3awueWqdp1OZudPelsEIgx'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/7kk9ucvRJim0NMM89Lml2Y'}, 'href': 'https://api.spotify.com/v1/artists/7kk9ucvRJim0NMM89Lml2Y', 'id': '7kk9ucvRJim0NMM89Lml2Y', 'name': 'MXZI', 'type': 'artist', 'uri': 'spotify:artist:7kk9ucvRJim0NMM89Lml2Y'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/55TpSGABb9xsmXHkqbv3ti'}, 'href': 'https://api.spotify.com/v1/artists/55TpSGABb9xsmXHkqbv3ti', 'id': '55TpSGABb9xsmXHkqbv3ti', 'name': 'Rushex', 'type': 'artist', 'uri': 'spotify:artist:55TpSGABb9xsmXHkqbv3ti'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/6gzkhdNfpMIPg91TnzlcCh'}, 'href': 'https://api.spotify.com/v1/artists/6gzkhdNfpMIPg91TnzlcCh', 'id': '6gzkhdNfpMIPg91TnzlcCh', 'name': 'MONTAGEM', 'type': 'artist', 'uri': 'spotify:artist:6gzkhdNfpMIPg91TnzlcCh'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/0jrirfCZkRU3iA2sH9JEko'}, 'href': 'https://api.spotify.com/v1/artists/0jrirfCZkRU3iA2sH9JEko', 'id': '0jrirfCZkRU3iA2sH9JEko', 'name': 'Repsaj', 'type': 'artist', 'uri': 'spotify:artist:0jrirfCZkRU3iA2sH9JEko'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/7kk9ucvRJim0NMM89Lml2Y'}, 'href': 'https://api.spotify.com/v1/artists/7kk9ucvRJim0NMM89Lml2Y', 'id': '7kk9ucvRJim0NMM89Lml2Y', 'name': 'MXZI', 'type': 'artist', 'uri': 'spotify:artist:7kk9ucvRJim0NMM89Lml2Y'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/5SCDfg1YoEfI5gFtXqEWah'}, 'href': 'https://api.spotify.com/v1/artists/5SCDfg1YoEfI5gFtXqEWah', 'id': '5SCDfg1YoEfI5gFtXqEWah', 'name': 'ATLXS', 'type': 'artist', 'uri': 'spotify:artist:5SCDfg1YoEfI5gFtXqEWah'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/34giN3qeTOdgDSJIdtIMdm'}, 'href': 'https://api.spotify.com/v1/artists/34giN3qeTOdgDSJIdtIMdm', 'id': '34giN3qeTOdgDSJIdtIMdm', 'name': 'Mc Jhey', 'type': 'artist', 'uri': 'spotify:artist:34giN3qeTOdgDSJIdtIMdm'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/5bePP411ITzZyWf1QZ2SX4'}, 'href': 'https://api.spotify.com/v1/artists/5bePP411ITzZyWf1QZ2SX4', 'id': '5bePP411ITzZyWf1QZ2SX4', 'name': 'Flame Runner', 'type': 'artist', 'uri': 'spotify:artist:5bePP411ITzZyWf1QZ2SX4'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/7qIgmxSjoXEeifSVDh8nIt'}, 'href': 'https://api.spotify.com/v1/artists/7qIgmxSjoXEeifSVDh8nIt', 'id': '7qIgmxSjoXEeifSVDh8nIt', 'name': 'MXCCREE', 'type': 'artist', 'uri': 'spotify:artist:7qIgmxSjoXEeifSVDh8nIt'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/1dX1zejt24Ojiu0lX4T1ZM'}, 'href': 'https://api.spotify.com/v1/artists/1dX1zejt24Ojiu0lX4T1ZM', 'id': '1dX1zejt24Ojiu0lX4T1ZM', 'name': 'DJ GL3CHEKY', 'type': 'artist', 'uri': 'spotify:artist:1dX1zejt24Ojiu0lX4T1ZM'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/0Vxqvpm9tpZcz6d4egDtjX'}, 'href': 'https://api.spotify.com/v1/artists/0Vxqvpm9tpZcz6d4egDtjX', 'id': '0Vxqvpm9tpZcz6d4egDtjX', 'name': 'MC PR', 'type': 'artist', 'uri': 'spotify:artist:0Vxqvpm9tpZcz6d4egDtjX'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/2vKxv2oKVSEJZ1VmuLUOvY'}, 'href': 'https://api.spotify.com/v1/artists/2vKxv2oKVSEJZ1VmuLUOvY', 'id': '2vKxv2oKVSEJZ1VmuLUOvY', 'name': 'Irokz', 'type': 'artist', 'uri': 'spotify:artist:2vKxv2oKVSEJZ1VmuLUOvY'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/6s4LSwgbzTAfnN6OUfegJB'}, 'href': 'https://api.spotify.com/v1/artists/6s4LSwgbzTAfnN6OUfegJB', 'id': '6s4LSwgbzTAfnN6OUfegJB', 'name': 'Sayfalse', 'type': 'artist', 'uri': 'spotify:artist:6s4LSwgbzTAfnN6OUfegJB'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/02wf6SCDwrs2qTX09X0IRE'}, 'href': 'https://api.spotify.com/v1/artists/02wf6SCDwrs2qTX09X0IRE', 'id': '02wf6SCDwrs2qTX09X0IRE', 'name': "Yb Wasg'ood", 'type': 'artist', 'uri': 'spotify:artist:02wf6SCDwrs2qTX09X0IRE'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/09cKncAQn28NqTUORLMwSR'}, 'href': 'https://api.spotify.com/v1/artists/09cKncAQn28NqTUORLMwSR', 'id': '09cKncAQn28NqTUORLMwSR', 'name': 'Ariis', 'type': 'artist', 'uri': 'spotify:artist:09cKncAQn28NqTUORLMwSR'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/02wf6SCDwrs2qTX09X0IRE'}, 'href': 'https://api.spotify.com/v1/artists/02wf6SCDwrs2qTX09X0IRE', 'id': '02wf6SCDwrs2qTX09X0IRE', 'name': "Yb Wasg'ood", 'type': 'artist', 'uri': 'spotify:artist:02wf6SCDwrs2qTX09X0IRE'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/09cKncAQn28NqTUORLMwSR'}, 'href': 'https://api.spotify.com/v1/artists/09cKncAQn28NqTUORLMwSR', 'id': '09cKncAQn28NqTUORLMwSR', 'name': 'Ariis', 'type': 'artist', 'uri': 'spotify:artist:09cKncAQn28NqTUORLMwSR'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/2nGwC9QG6Hpw4fSDgNpn5n'}, 'href': 'https://api.spotify.com/v1/artists/2nGwC9QG6Hpw4fSDgNpn5n', 'id': '2nGwC9QG6Hpw4fSDgNpn5n', 'name': 'JXM', 'type': 'artist', 'uri': 'spotify:artist:2nGwC9QG6Hpw4fSDgNpn5n'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/4DWPOsGWbW7sBHb1UuBvWs'}, 'href': 'https://api.spotify.com/v1/artists/4DWPOsGWbW7sBHb1UuBvWs', 'id': '4DWPOsGWbW7sBHb1UuBvWs', 'name': 'Polaris', 'type': 'artist', 'uri': 'spotify:artist:4DWPOsGWbW7sBHb1UuBvWs'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/4nl0CCx6PpEOOr2Z2ThPdp'}, 'href': 'https://api.spotify.com/v1/artists/4nl0CCx6PpEOOr2Z2ThPdp', 'id': '4nl0CCx6PpEOOr2Z2ThPdp', 'name': 'xxanteria', 'type': 'artist', 'uri': 'spotify:artist:4nl0CCx6PpEOOr2Z2ThPdp'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/6JjQbtAO09K7qBEW2pdX5s'}, 'href': 'https://api.spotify.com/v1/artists/6JjQbtAO09K7qBEW2pdX5s', 'id': '6JjQbtAO09K7qBEW2pdX5s', 'name': 'isq', 'type': 'artist', 'uri': 'spotify:artist:6JjQbtAO09K7qBEW2pdX5s'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/09cKncAQn28NqTUORLMwSR'}, 'href': 'https://api.spotify.com/v1/artists/09cKncAQn28NqTUORLMwSR', 'id': '09cKncAQn28NqTUORLMwSR', 'name': 'Ariis', 'type': 'artist', 'uri': 'spotify:artist:09cKncAQn28NqTUORLMwSR'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/2vPnS0IpayC2RVFuQA08R4'}, 'href': 'https://api.spotify.com/v1/artists/2vPnS0IpayC2RVFuQA08R4', 'id': '2vPnS0IpayC2RVFuQA08R4', 'name': '2KE', 'type': 'artist', 'uri': 'spotify:artist:2vPnS0IpayC2RVFuQA08R4'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/4jM6R2LK78dVTqHVUoA4li'}, 'href': 'https://api.spotify.com/v1/artists/4jM6R2LK78dVTqHVUoA4li', 'id': '4jM6R2LK78dVTqHVUoA4li', 'name': '808iuli', 'type': 'artist', 'uri': 'spotify:artist:4jM6R2LK78dVTqHVUoA4li'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/1Sdc6ySbIvzO0X9vbyHzWm'}, 'href': 'https://api.spotify.com/v1/artists/1Sdc6ySbIvzO0X9vbyHzWm', 'id': '1Sdc6ySbIvzO0X9vbyHzWm', 'name': 'Ogryzek', 'type': 'artist', 'uri': 'spotify:artist:1Sdc6ySbIvzO0X9vbyHzWm'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/5tvPbCrx8LMaL9Zby5e7c2'}, 'href': 'https://api.spotify.com/v1/artists/5tvPbCrx8LMaL9Zby5e7c2', 'id': '5tvPbCrx8LMaL9Zby5e7c2', 'name': 'fennecxx', 'type': 'artist', 'uri': 'spotify:artist:5tvPbCrx8LMaL9Zby5e7c2'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/7FqHcUwnhxJZAgS3I6GFFL'}, 'href': 'https://api.spotify.com/v1/artists/7FqHcUwnhxJZAgS3I6GFFL', 'id': '7FqHcUwnhxJZAgS3I6GFFL', 'name': 'DJ ALEX', 'type': 'artist', 'uri': 'spotify:artist:7FqHcUwnhxJZAgS3I6GFFL'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/0oGN0s7dqyWbR41yMsNs0R'}, 'href': 'https://api.spotify.com/v1/artists/0oGN0s7dqyWbR41yMsNs0R', 'id': '0oGN0s7dqyWbR41yMsNs0R', 'name': 'princce', 'type': 'artist', 'uri': 'spotify:artist:0oGN0s7dqyWbR41yMsNs0R'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/2YXKTfoEjKVzCNI0J6rHbQ'}, 'href': 'https://api.spotify.com/v1/artists/2YXKTfoEjKVzCNI0J6rHbQ', 'id': '2YXKTfoEjKVzCNI0J6rHbQ', 'name': 'FR3ST', 'type': 'artist', 'uri': 'spotify:artist:2YXKTfoEjKVzCNI0J6rHbQ'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/1Sdc6ySbIvzO0X9vbyHzWm'}, 'href': 'https://api.spotify.com/v1/artists/1Sdc6ySbIvzO0X9vbyHzWm', 'id': '1Sdc6ySbIvzO0X9vbyHzWm', 'name': 'Ogryzek', 'type': 'artist', 'uri': 'spotify:artist:1Sdc6ySbIvzO0X9vbyHzWm'}
{'external_urls': {'spotify': 'https://open.spotify.com/artist/3qycxIGAHj1KyoAQ6PGCO6'}, 'href': 'https://api.spotify.com/v1/artists/3qycxIGAHj1KyoAQ6PGCO6', 'id': '3qycxIGAHj1KyoAQ6PGCO6', 'name': 'Seek', 'type': 'artist', 'uri': 'spotify:artist:3qycxIGAHj1KyoAQ6PGCO6'}

In [96]:
artist_list = []
for row in data['items']:
    for key, value in row.items():
        if key == 'track':
            for artist in value['artists']:
               artist_dict = {'artist_id' : artist['id'],'external_urls' : artist['href'], 'name' : artist['name'] }
               artist_list.append(artist_dict)

In [97]:
artist_list

[{'artist_id': '5SCDfg1YoEfI5gFtXqEWah',
  'external_urls': 'https://api.spotify.com/v1/artists/5SCDfg1YoEfI5gFtXqEWah',
  'name': 'ATLXS'},
 {'artist_id': '6hB4Px9Gm2FjAB30PXsv8K',
  'external_urls': 'https://api.spotify.com/v1/artists/6hB4Px9Gm2FjAB30PXsv8K',
  'name': 'cape'},
 {'artist_id': '62vwt2P3iBw4NwHdDZb27q',
  'external_urls': 'https://api.spotify.com/v1/artists/62vwt2P3iBw4NwHdDZb27q',
  'name': 'JXNDRO'},
 {'artist_id': '6s4LSwgbzTAfnN6OUfegJB',
  'external_urls': 'https://api.spotify.com/v1/artists/6s4LSwgbzTAfnN6OUfegJB',
  'name': 'Sayfalse'},
 {'artist_id': '5tIkxADHN80ca0K6HCpWIt',
  'external_urls': 'https://api.spotify.com/v1/artists/5tIkxADHN80ca0K6HCpWIt',
  'name': 'ZXKAI'},
 {'artist_id': '1M02J1PLobtQYok93DEvVa',
  'external_urls': 'https://api.spotify.com/v1/artists/1M02J1PLobtQYok93DEvVa',
  'name': 'slxughter'},
 {'artist_id': '1RklNDIiYVZ3dYdEUnB0cS',
  'external_urls': 'https://api.spotify.com/v1/artists/1RklNDIiYVZ3dYdEUnB0cS',
  'name': 'ANDROMEDA'},
 {'artist_id': '51K0b3lRd87cKX02hU26we',
  'external_urls': 'https://api.spotify.com/v1/artists/51K0b3lRd87cKX02hU26we',
  'name': 'elysian.'},
 {'artist_id': '1yevH7mkPMXeSTnA9SwHvq',
  'external_urls': 'https://api.spotify.com/v1/artists/1yevH7mkPMXeSTnA9SwHvq',
  'name': 'SEKIMANE'},
 {'artist_id': '5dDNNq04RjKXFOADdHd6VX',
  'external_urls': 'https://api.spotify.com/v1/artists/5dDNNq04RjKXFOADdHd6VX',
  'name': 'Scythermane'},
 {'artist_id': '7lAaAGxYxk2GH8cMbTEwAL',
  'external_urls': 'https://api.spotify.com/v1/artists/7lAaAGxYxk2GH8cMbTEwAL',
  'name': 'NXGHT!'},
 {'artist_id': '26COCLBHY0CCqCbSlIKWee',
  'external_urls': 'https://api.spotify.com/v1/artists/26COCLBHY0CCqCbSlIKWee',
  'name': 'DJ DYLANFK'},
 {'artist_id': '23zmS2d4hkOtvBlJ6T5dqM',
  'external_urls': 'https://api.spotify.com/v1/artists/23zmS2d4hkOtvBlJ6T5dqM',
  'name': 'KGJ'},
 {'artist_id': '5dDNNq04RjKXFOADdHd6VX',
  'external_urls': 'https://api.spotify.com/v1/artists/5dDNNq04RjKXFOADdHd6VX',
  'name': 'Scythermane'},
 {'artist_id': '7lAaAGxYxk2GH8cMbTEwAL',
  'external_urls': 'https://api.spotify.com/v1/artists/7lAaAGxYxk2GH8cMbTEwAL',
  'name': 'NXGHT!'},
 {'artist_id': '14hsjenLEdvafsGkk2CEiF',
  'external_urls': 'https://api.spotify.com/v1/artists/14hsjenLEdvafsGkk2CEiF',
  'name': 'MC Fabinho da Osk'},
 {'artist_id': '3SENePgknpJt3DvLK2JAfZ',
  'external_urls': 'https://api.spotify.com/v1/artists/3SENePgknpJt3DvLK2JAfZ',
  'name': 'KHAOS'},
 {'artist_id': '2q5vFLZus8uaVSzmIwH4Tz',
  'external_urls': 'https://api.spotify.com/v1/artists/2q5vFLZus8uaVSzmIwH4Tz',
  'name': 'Jmilton'},
 {'artist_id': '1P2tOPRmSa1XzEdtIEYA9W',
  'external_urls': 'https://api.spotify.com/v1/artists/1P2tOPRmSa1XzEdtIEYA9W',
  'name': 'Mc Jajá'},
 {'artist_id': '1kd6WqngBvP0Vthu1sGI0j',
  'external_urls': 'https://api.spotify.com/v1/artists/1kd6WqngBvP0Vthu1sGI0j',
  'name': 'Nakama'},
 {'artist_id': '2Q3xviVw2VXFRXtsF2gpR1',
  'external_urls': 'https://api.spotify.com/v1/artists/2Q3xviVw2VXFRXtsF2gpR1',
  'name': 'ΣP'},
 {'artist_id': '6s4LSwgbzTAfnN6OUfegJB',
  'external_urls': 'https://api.spotify.com/v1/artists/6s4LSwgbzTAfnN6OUfegJB',
  'name': 'Sayfalse'},
 {'artist_id': '2LWzzk1DrqcGB0h3ezY8qo',
  'external_urls': 'https://api.spotify.com/v1/artists/2LWzzk1DrqcGB0h3ezY8qo',
  'name': 'SNXP'},
 {'artist_id': '6HwL7jLVz0vywuLyHq3ozr',
  'external_urls': 'https://api.spotify.com/v1/artists/6HwL7jLVz0vywuLyHq3ozr',
  'name': 'ßino'},
 {'artist_id': '5bePP411ITzZyWf1QZ2SX4',
  'external_urls': 'https://api.spotify.com/v1/artists/5bePP411ITzZyWf1QZ2SX4',
  'name': 'Flame Runner'},
 {'artist_id': '3g0UoyvaTaHUrfpHiRqsD1',
  'external_urls': 'https://api.spotify.com/v1/artists/3g0UoyvaTaHUrfpHiRqsD1',
  'name': 'Nateki'},
 {'artist_id': '5dDNNq04RjKXFOADdHd6VX',
  'external_urls': 'https://api.spotify.com/v1/artists/5dDNNq04RjKXFOADdHd6VX',
  'name': 'Scythermane'},
 {'artist_id': '10mKIVPFtg42JIvttHQrzr',
  'external_urls': 'https://api.spotify.com/v1/artists/10mKIVPFtg42JIvttHQrzr',
  'name': 'MC MAYAH'},
 {'artist_id': '2q5vFLZus8uaVSzmIwH4Tz',
  'external_urls': 'https://api.spotify.com/v1/artists/2q5vFLZus8uaVSzmIwH4Tz',
  'name': 'Jmilton'},
 {'artist_id': '67PBOFpTBFaNkhz5IouBwi',
  'external_urls': 'https://api.spotify.com/v1/artists/67PBOFpTBFaNkhz5IouBwi',
  'name': 'MC Xangai'},
 {'artist_id': '1Fl1fc7bZfRVUCffh9Uudx',
  'external_urls': 'https://api.spotify.com/v1/artists/1Fl1fc7bZfRVUCffh9Uudx',
  'name': 'sma$her'},
 {'artist_id': '7kk9ucvRJim0NMM89Lml2Y',
  'external_urls': 'https://api.spotify.com/v1/artists/7kk9ucvRJim0NMM89Lml2Y',
  'name': 'MXZI'},
 {'artist_id': '7kk9ucvRJim0NMM89Lml2Y',
  'external_urls': 'https://api.spotify.com/v1/artists/7kk9ucvRJim0NMM89Lml2Y',
  'name': 'MXZI'},
 {'artist_id': '6s4LSwgbzTAfnN6OUfegJB',
  'external_urls': 'https://api.spotify.com/v1/artists/6s4LSwgbzTAfnN6OUfegJB',
  'name': 'Sayfalse'},
 {'artist_id': '5dDNNq04RjKXFOADdHd6VX',
  'external_urls': 'https://api.spotify.com/v1/artists/5dDNNq04RjKXFOADdHd6VX',
  'name': 'Scythermane'},
 {'artist_id': '7kk9ucvRJim0NMM89Lml2Y',
  'external_urls': 'https://api.spotify.com/v1/artists/7kk9ucvRJim0NMM89Lml2Y',
  'name': 'MXZI'},
 {'artist_id': '6U0dJxYVB41L8WDZ02Nwuk',
  'external_urls': 'https://api.spotify.com/v1/artists/6U0dJxYVB41L8WDZ02Nwuk',
  'name': 'Dj Samir'},
 {'artist_id': '0JGZRsRtFTQ0ZVBq9b2ZEj',
  'external_urls': 'https://api.spotify.com/v1/artists/0JGZRsRtFTQ0ZVBq9b2ZEj',
  'name': 'DJ Javi26'},
 {'artist_id': '0exQbKNFd9pLmdIGycwmlf',
  'external_urls': 'https://api.spotify.com/v1/artists/0exQbKNFd9pLmdIGycwmlf',
  'name': 'h6itam'},
 {'artist_id': '1kd6WqngBvP0Vthu1sGI0j',
  'external_urls': 'https://api.spotify.com/v1/artists/1kd6WqngBvP0Vthu1sGI0j',
  'name': 'Nakama'},
 {'artist_id': '3awueWqdp1OZudPelsEIgx',
  'external_urls': 'https://api.spotify.com/v1/artists/3awueWqdp1OZudPelsEIgx',
  'name': 'Mc Staff'},
 {'artist_id': '7kk9ucvRJim0NMM89Lml2Y',
  'external_urls': 'https://api.spotify.com/v1/artists/7kk9ucvRJim0NMM89Lml2Y',
  'name': 'MXZI'},
 {'artist_id': '55TpSGABb9xsmXHkqbv3ti',
  'external_urls': 'https://api.spotify.com/v1/artists/55TpSGABb9xsmXHkqbv3ti',
  'name': 'Rushex'},
 {'artist_id': '6gzkhdNfpMIPg91TnzlcCh',
  'external_urls': 'https://api.spotify.com/v1/artists/6gzkhdNfpMIPg91TnzlcCh',
  'name': 'MONTAGEM'},
 {'artist_id': '0jrirfCZkRU3iA2sH9JEko',
  'external_urls': 'https://api.spotify.com/v1/artists/0jrirfCZkRU3iA2sH9JEko',
  'name': 'Repsaj'},
 {'artist_id': '7kk9ucvRJim0NMM89Lml2Y',
  'external_urls': 'https://api.spotify.com/v1/artists/7kk9ucvRJim0NMM89Lml2Y',
  'name': 'MXZI'},
 {'artist_id': '5SCDfg1YoEfI5gFtXqEWah',
  'external_urls': 'https://api.spotify.com/v1/artists/5SCDfg1YoEfI5gFtXqEWah',
  'name': 'ATLXS'},
 {'artist_id': '34giN3qeTOdgDSJIdtIMdm',
  'external_urls': 'https://api.spotify.com/v1/artists/34giN3qeTOdgDSJIdtIMdm',
  'name': 'Mc Jhey'},
 {'artist_id': '5bePP411ITzZyWf1QZ2SX4',
  'external_urls': 'https://api.spotify.com/v1/artists/5bePP411ITzZyWf1QZ2SX4',
  'name': 'Flame Runner'},
 {'artist_id': '7qIgmxSjoXEeifSVDh8nIt',
  'external_urls': 'https://api.spotify.com/v1/artists/7qIgmxSjoXEeifSVDh8nIt',
  'name': 'MXCCREE'},
 {'artist_id': '1dX1zejt24Ojiu0lX4T1ZM',
  'external_urls': 'https://api.spotify.com/v1/artists/1dX1zejt24Ojiu0lX4T1ZM',
  'name': 'DJ GL3CHEKY'},
 {'artist_id': '0Vxqvpm9tpZcz6d4egDtjX',
  'external_urls': 'https://api.spotify.com/v1/artists/0Vxqvpm9tpZcz6d4egDtjX',
  'name': 'MC PR'},
 {'artist_id': '2vKxv2oKVSEJZ1VmuLUOvY',
  'external_urls': 'https://api.spotify.com/v1/artists/2vKxv2oKVSEJZ1VmuLUOvY',
  'name': 'Irokz'},
 {'artist_id': '6s4LSwgbzTAfnN6OUfegJB',
  'external_urls': 'https://api.spotify.com/v1/artists/6s4LSwgbzTAfnN6OUfegJB',
  'name': 'Sayfalse'},
 {'artist_id': '02wf6SCDwrs2qTX09X0IRE',
  'external_urls': 'https://api.spotify.com/v1/artists/02wf6SCDwrs2qTX09X0IRE',
  'name': "Yb Wasg'ood"},
 {'artist_id': '09cKncAQn28NqTUORLMwSR',
  'external_urls': 'https://api.spotify.com/v1/artists/09cKncAQn28NqTUORLMwSR',
  'name': 'Ariis'},
 {'artist_id': '02wf6SCDwrs2qTX09X0IRE',
  'external_urls': 'https://api.spotify.com/v1/artists/02wf6SCDwrs2qTX09X0IRE',
  'name': "Yb Wasg'ood"},
 {'artist_id': '09cKncAQn28NqTUORLMwSR',
  'external_urls': 'https://api.spotify.com/v1/artists/09cKncAQn28NqTUORLMwSR',
  'name': 'Ariis'},
 {'artist_id': '2nGwC9QG6Hpw4fSDgNpn5n',
  'external_urls': 'https://api.spotify.com/v1/artists/2nGwC9QG6Hpw4fSDgNpn5n',
  'name': 'JXM'},
 {'artist_id': '4DWPOsGWbW7sBHb1UuBvWs',
  'external_urls': 'https://api.spotify.com/v1/artists/4DWPOsGWbW7sBHb1UuBvWs',
  'name': 'Polaris'},
 {'artist_id': '4nl0CCx6PpEOOr2Z2ThPdp',
  'external_urls': 'https://api.spotify.com/v1/artists/4nl0CCx6PpEOOr2Z2ThPdp',
  'name': 'xxanteria'},
 {'artist_id': '6JjQbtAO09K7qBEW2pdX5s',
  'external_urls': 'https://api.spotify.com/v1/artists/6JjQbtAO09K7qBEW2pdX5s',
  'name': 'isq'},
 {'artist_id': '09cKncAQn28NqTUORLMwSR',
  'external_urls': 'https://api.spotify.com/v1/artists/09cKncAQn28NqTUORLMwSR',
  'name': 'Ariis'},
 {'artist_id': '2vPnS0IpayC2RVFuQA08R4',
  'external_urls': 'https://api.spotify.com/v1/artists/2vPnS0IpayC2RVFuQA08R4',
  'name': '2KE'},
 {'artist_id': '4jM6R2LK78dVTqHVUoA4li',
  'external_urls': 'https://api.spotify.com/v1/artists/4jM6R2LK78dVTqHVUoA4li',
  'name': '808iuli'},
 {'artist_id': '1Sdc6ySbIvzO0X9vbyHzWm',
  'external_urls': 'https://api.spotify.com/v1/artists/1Sdc6ySbIvzO0X9vbyHzWm',
  'name': 'Ogryzek'},
 {'artist_id': '5tvPbCrx8LMaL9Zby5e7c2',
  'external_urls': 'https://api.spotify.com/v1/artists/5tvPbCrx8LMaL9Zby5e7c2',
  'name': 'fennecxx'},
 {'artist_id': '7FqHcUwnhxJZAgS3I6GFFL',
  'external_urls': 'https://api.spotify.com/v1/artists/7FqHcUwnhxJZAgS3I6GFFL',
  'name': 'DJ ALEX'},
 {'artist_id': '0oGN0s7dqyWbR41yMsNs0R',
  'external_urls': 'https://api.spotify.com/v1/artists/0oGN0s7dqyWbR41yMsNs0R',
  'name': 'princce'},
 {'artist_id': '2YXKTfoEjKVzCNI0J6rHbQ',
  'external_urls': 'https://api.spotify.com/v1/artists/2YXKTfoEjKVzCNI0J6rHbQ',
  'name': 'FR3ST'},
 {'artist_id': '1Sdc6ySbIvzO0X9vbyHzWm',
  'external_urls': 'https://api.spotify.com/v1/artists/1Sdc6ySbIvzO0X9vbyHzWm',
  'name': 'Ogryzek'},
 {'artist_id': '3qycxIGAHj1KyoAQ6PGCO6',
  'external_urls': 'https://api.spotify.com/v1/artists/3qycxIGAHj1KyoAQ6PGCO6',
  'name': 'Seek'},
 {'artist_id': '1nccv1GNVkBdvsYi2FB5FB',
  'external_urls': 'https://api.spotify.com/v1/artists/1nccv1GNVkBdvsYi2FB5FB',
  'name': 'NUEKI'},
 {'artist_id': '23P2mSsBpPkfR9fTrOc1a4',
  'external_urls': 'https://api.spotify.com/v1/artists/23P2mSsBpPkfR9fTrOc1a4',
  'name': 'TOLCHONOV'},
 {'artist_id': '700c9Qz2z6HZKTumeliKAw',
  'external_urls': 'https://api.spotify.com/v1/artists/700c9Qz2z6HZKTumeliKAw',
  'name': 'LONOWN'},
 {'artist_id': '4nl0CCx6PpEOOr2Z2ThPdp',
  'external_urls': 'https://api.spotify.com/v1/artists/4nl0CCx6PpEOOr2Z2ThPdp',
  'name': 'xxanteria'},
 {'artist_id': '6BWtcMF39LT5Db5FT54YYG',
  'external_urls': 'https://api.spotify.com/v1/artists/6BWtcMF39LT5Db5FT54YYG',
  'name': 'NCTS'},
 {'artist_id': '6rzNFUmaEVnYb8kzh9tBTt',
  'external_urls': 'https://api.spotify.com/v1/artists/6rzNFUmaEVnYb8kzh9tBTt',
  'name': 'CURSEDEVIL'},
 {'artist_id': '3QMpCp3GHiHXgnX1LldXWe',
  'external_urls': 'https://api.spotify.com/v1/artists/3QMpCp3GHiHXgnX1LldXWe',
  'name': 'DJ FKU'},
 {'artist_id': '3voCipmmrW5uF4EMA6aSbj',
  'external_urls': 'https://api.spotify.com/v1/artists/3voCipmmrW5uF4EMA6aSbj',
  'name': 'Skorde'},
 {'artist_id': '6s4LSwgbzTAfnN6OUfegJB',
  'external_urls': 'https://api.spotify.com/v1/artists/6s4LSwgbzTAfnN6OUfegJB',
  'name': 'Sayfalse'},
 {'artist_id': '62D4KEvQMmmK88mTkkWx6Q',
  'external_urls': 'https://api.spotify.com/v1/artists/62D4KEvQMmmK88mTkkWx6Q',
  'name': 'RD12'},
 {'artist_id': '3rt96VXGtEgD4uSOJ6B69H',
  'external_urls': 'https://api.spotify.com/v1/artists/3rt96VXGtEgD4uSOJ6B69H',
  'name': 'TRASHXRL'},
 {'artist_id': '3l4fsEzoeabsET7ddv0lZW',
  'external_urls': 'https://api.spotify.com/v1/artists/3l4fsEzoeabsET7ddv0lZW',
  'name': 'Mc Delux'},
 {'artist_id': '5IpS1TN1Crp8Ym4zjiIrtK',
  'external_urls': 'https://api.spotify.com/v1/artists/5IpS1TN1Crp8Ym4zjiIrtK',
  'name': 'LXNGVX'},
 {'artist_id': '6kLsCQ1gKvJmjmC8XbfqFE',
  'external_urls': 'https://api.spotify.com/v1/artists/6kLsCQ1gKvJmjmC8XbfqFE',
  'name': 'VISXGE'},
 {'artist_id': '5AviPhK4XqgGjtTa0m9aQc',
  'external_urls': 'https://api.spotify.com/v1/artists/5AviPhK4XqgGjtTa0m9aQc',
  'name': 'NAOMI'},
 {'artist_id': '2UKmwMB2wMQMvQcduijrQi',
  'external_urls': 'https://api.spotify.com/v1/artists/2UKmwMB2wMQMvQcduijrQi',
  'name': 'DRAWMEDEATH'},
 {'artist_id': '3rt96VXGtEgD4uSOJ6B69H',
  'external_urls': 'https://api.spotify.com/v1/artists/3rt96VXGtEgD4uSOJ6B69H',
  'name': 'TRASHXRL'},
 {'artist_id': '0ivrHNM8urVaCkgRX8rtKH',
  'external_urls': 'https://api.spotify.com/v1/artists/0ivrHNM8urVaCkgRX8rtKH',
  'name': 'Mc Menor Do Alvorada'},
 {'artist_id': '65FHTCI8EmW94W0TdWb8ja',
  'external_urls': 'https://api.spotify.com/v1/artists/65FHTCI8EmW94W0TdWb8ja',
  'name': 'Slowboy'},
 {'artist_id': '1nccv1GNVkBdvsYi2FB5FB',
  'external_urls': 'https://api.spotify.com/v1/artists/1nccv1GNVkBdvsYi2FB5FB',
  'name': 'NUEKI'},
 {'artist_id': '6QwlKB1hO357wh5oNuuInl',
  'external_urls': 'https://api.spotify.com/v1/artists/6QwlKB1hO357wh5oNuuInl',
  'name': 'Crazy Mano'},
 {'artist_id': '23P2mSsBpPkfR9fTrOc1a4',
  'external_urls': 'https://api.spotify.com/v1/artists/23P2mSsBpPkfR9fTrOc1a4',
  'name': 'TOLCHONOV'},
 {'artist_id': '6ZhleMHIGIpjkBHrQDl4G7',
  'external_urls': 'https://api.spotify.com/v1/artists/6ZhleMHIGIpjkBHrQDl4G7',
  'name': 'DYGO'},
 {'artist_id': '1KoTNs0Ev2KGs7AF5lWlx3',
  'external_urls': 'https://api.spotify.com/v1/artists/1KoTNs0Ev2KGs7AF5lWlx3',
  'name': 'Mxng0'},
 {'artist_id': '07MaeHw0cyfmgQ9D9I61UT',
  'external_urls': 'https://api.spotify.com/v1/artists/07MaeHw0cyfmgQ9D9I61UT',
  'name': 'DJ JEEAN 011'},
 {'artist_id': '7vfisrjZ6AMRo5vNVLP3qQ',
  'external_urls': 'https://api.spotify.com/v1/artists/7vfisrjZ6AMRo5vNVLP3qQ',
  'name': 'MC BM OFICIAL'},
 {'artist_id': '0exQbKNFd9pLmdIGycwmlf',
  'external_urls': 'https://api.spotify.com/v1/artists/0exQbKNFd9pLmdIGycwmlf',
  'name': 'h6itam'},
 {'artist_id': '4o5PswOvXGSq0y5BqZTR9n',
  'external_urls': 'https://api.spotify.com/v1/artists/4o5PswOvXGSq0y5BqZTR9n',
  'name': 'STRAWANGLE'},
 {'artist_id': '2JrpgVMFW3Hpe1CwLaAORl',
  'external_urls': 'https://api.spotify.com/v1/artists/2JrpgVMFW3Hpe1CwLaAORl',
  'name': 'MC RP VK'},
 {'artist_id': '2ge1WtiBqengw0nAnq94Zo',
  'external_urls': 'https://api.spotify.com/v1/artists/2ge1WtiBqengw0nAnq94Zo',
  'name': 'MC Da 12'},
 {'artist_id': '6JjQbtAO09K7qBEW2pdX5s',
  'external_urls': 'https://api.spotify.com/v1/artists/6JjQbtAO09K7qBEW2pdX5s',
  'name': 'isq'},
 {'artist_id': '7lAaAGxYxk2GH8cMbTEwAL',
  'external_urls': 'https://api.spotify.com/v1/artists/7lAaAGxYxk2GH8cMbTEwAL',
  'name': 'NXGHT!'},
 {'artist_id': '3wQNcarvRuzhz2Fg1pVDxZ',
  'external_urls': 'https://api.spotify.com/v1/artists/3wQNcarvRuzhz2Fg1pVDxZ',
  'name': 'DJ ANXVAR'},
 {'artist_id': '1HJglK87YzctjxETSJqh64',
  'external_urls': 'https://api.spotify.com/v1/artists/1HJglK87YzctjxETSJqh64',
  'name': 'DJ ZAP'},
 {'artist_id': '4H61c3XQu4PswXGtB0MJ6N',
  'external_urls': 'https://api.spotify.com/v1/artists/4H61c3XQu4PswXGtB0MJ6N',
  'name': 'Hexora'},
 {'artist_id': '6WCBS0WuEBBtdV7TZMtCnh',
  'external_urls': 'https://api.spotify.com/v1/artists/6WCBS0WuEBBtdV7TZMtCnh',
  'name': 'Artox'},
 {'artist_id': '4epIlGy9RGEMdrfSXS2HEc',
  'external_urls': 'https://api.spotify.com/v1/artists/4epIlGy9RGEMdrfSXS2HEc',
  'name': 'Alert'},
 {'artist_id': '5Vd9shhZpzTYaaZ6KQNnjU',
  'external_urls': 'https://api.spotify.com/v1/artists/5Vd9shhZpzTYaaZ6KQNnjU',
  'name': 'GLXXMSTRIDER'},
 {'artist_id': '3Xd2WSaNywx5gn1pgRPFjF',
  'external_urls': 'https://api.spotify.com/v1/artists/3Xd2WSaNywx5gn1pgRPFjF',
  'name': 'Eternxlkz'},
 {'artist_id': '648ZoUpTM6iIMTCgo3lLCE',
  'external_urls': 'https://api.spotify.com/v1/artists/648ZoUpTM6iIMTCgo3lLCE',
  'name': 'DJ Paulinho Mondi Da Baixa Baviera'},
 {'artist_id': '0sjGfRBmq6lKmUNgt8Ptic',
  'external_urls': 'https://api.spotify.com/v1/artists/0sjGfRBmq6lKmUNgt8Ptic',
  'name': 'Mc Vitorioso'},
 {'artist_id': '60vF1fLR6yzLxCQUlnAYYj',
  'external_urls': 'https://api.spotify.com/v1/artists/60vF1fLR6yzLxCQUlnAYYj',
  'name': '$werve'},
 {'artist_id': '5UKXrvmyouEgmvon7DwwzA',
  'external_urls': 'https://api.spotify.com/v1/artists/5UKXrvmyouEgmvon7DwwzA',
  'name': 'FXRCE'},
 {'artist_id': '7dUNKhz7HdxExteqcREGLi',
  'external_urls': 'https://api.spotify.com/v1/artists/7dUNKhz7HdxExteqcREGLi',
  'name': 'Mc Denny'},
 {'artist_id': '1yTrrABG9Vr2Y9lbHupN3f',
  'external_urls': 'https://api.spotify.com/v1/artists/1yTrrABG9Vr2Y9lbHupN3f',
  'name': 'DJ Vilão DS'},
 {'artist_id': '4kEtpjbEnSh4WNeLF1IeG7',
  'external_urls': 'https://api.spotify.com/v1/artists/4kEtpjbEnSh4WNeLF1IeG7',
  'name': 'MC Zudo Boladão'},
 {'artist_id': '3LfT6BvsnMomxucwVAXGiF',
  'external_urls': 'https://api.spotify.com/v1/artists/3LfT6BvsnMomxucwVAXGiF',
  'name': 'DJ Magrin Da DZ7'},
 {'artist_id': '2dZI1nDPMCgcymfUeLIObc',
  'external_urls': 'https://api.spotify.com/v1/artists/2dZI1nDPMCgcymfUeLIObc',
  'name': 'MC PH77'},
 {'artist_id': '4RsEAdLhbUy7j3zHWauPwF',
  'external_urls': 'https://api.spotify.com/v1/artists/4RsEAdLhbUy7j3zHWauPwF',
  'name': 'BLESSED MANE'},
 {'artist_id': '5IpS1TN1Crp8Ym4zjiIrtK',
  'external_urls': 'https://api.spotify.com/v1/artists/5IpS1TN1Crp8Ym4zjiIrtK',
  'name': 'LXNGVX'},
 {'artist_id': '0f1IECbrVV952unZkzrsg2',
  'external_urls': 'https://api.spotify.com/v1/artists/0f1IECbrVV952unZkzrsg2',
  'name': 'Mc Gw'},
 {'artist_id': '1iKfUld50BOVBIgHy3GlGt',
  'external_urls': 'https://api.spotify.com/v1/artists/1iKfUld50BOVBIgHy3GlGt',
  'name': 'DJ CEREJASS'},
 {'artist_id': '6s4LSwgbzTAfnN6OUfegJB',
  'external_urls': 'https://api.spotify.com/v1/artists/6s4LSwgbzTAfnN6OUfegJB',
  'name': 'Sayfalse'},
 {'artist_id': '09cKncAQn28NqTUORLMwSR',
  'external_urls': 'https://api.spotify.com/v1/artists/09cKncAQn28NqTUORLMwSR',
  'name': 'Ariis'},
 {'artist_id': '3uA4unR7LBOcqjpbOeCs0Y',
  'external_urls': 'https://api.spotify.com/v1/artists/3uA4unR7LBOcqjpbOeCs0Y',
  'name': '-Prey'},
 {'artist_id': '1TTHC3GlNDaE5eVoC3BVxm',
  'external_urls': 'https://api.spotify.com/v1/artists/1TTHC3GlNDaE5eVoC3BVxm',
  'name': 'Lumi Athena'},
 {'artist_id': '3yn6fs9MkW1i4V3S2G8Dxs',
  'external_urls': 'https://api.spotify.com/v1/artists/3yn6fs9MkW1i4V3S2G8Dxs',
  'name': 'vtze archive'},
 {'artist_id': '2RqjTHL40djgpNGG2LS9O0',
  'external_urls': 'https://api.spotify.com/v1/artists/2RqjTHL40djgpNGG2LS9O0',
  'name': 'Mc Ster'},
 {'artist_id': '3QMpCp3GHiHXgnX1LldXWe',
  'external_urls': 'https://api.spotify.com/v1/artists/3QMpCp3GHiHXgnX1LldXWe',
  'name': 'DJ FKU'},
 {'artist_id': '3wQNcarvRuzhz2Fg1pVDxZ',
  'external_urls': 'https://api.spotify.com/v1/artists/3wQNcarvRuzhz2Fg1pVDxZ',
  'name': 'DJ ANXVAR'},
 {'artist_id': '1nzIoHG5B7klgAPdwjqRDj',
  'external_urls': 'https://api.spotify.com/v1/artists/1nzIoHG5B7klgAPdwjqRDj',
  'name': 'MC LONE'},
 {'artist_id': '1PvcWjADPMezv8CTyJO9Uk',
  'external_urls': 'https://api.spotify.com/v1/artists/1PvcWjADPMezv8CTyJO9Uk',
  'name': 'Vermillion'},
 {'artist_id': '4cM6xcafBAbS9bOa8kAjRj',
  'external_urls': 'https://api.spotify.com/v1/artists/4cM6xcafBAbS9bOa8kAjRj',
  'name': 'ICEDMANE'},
 {'artist_id': '1pFLuMBwabtFITLNJlEZ9z',
  'external_urls': 'https://api.spotify.com/v1/artists/1pFLuMBwabtFITLNJlEZ9z',
  'name': 'DYSMANE'},
 {'artist_id': '3AbeBDqk7IsG1JZEWVVcpY',
  'external_urls': 'https://api.spotify.com/v1/artists/3AbeBDqk7IsG1JZEWVVcpY',
  'name': 'Mc Dido'},
 {'artist_id': '5Z56BMrvQB2rBAa5kffTPD',
  'external_urls': 'https://api.spotify.com/v1/artists/5Z56BMrvQB2rBAa5kffTPD',
  'name': 'HISTED'},
 {'artist_id': '4Rd0aHKGS9BdLYSXVvFjv5',
  'external_urls': 'https://api.spotify.com/v1/artists/4Rd0aHKGS9BdLYSXVvFjv5',
  'name': 'TXVSTERPLAYA'},

In [103]:
data['items'][0]['track']['name']

'PASSO BEM SOLTO - Slowed'

In [104]:
data['items'][0]['track'].keys()

dict_keys(['preview_url', 'available_markets', 'explicit', 'type', 'episode', 'track', 'album', 'artists', 'disc_number', 'track_number', 'duration_ms', 'external_ids', 'external_urls', 'href', 'id', 'name', 'popularity', 'uri', 'is_local'])

In [105]:
songs_list = []
for row in data['items']:
    song_id = row['track']['id']
    song_name = row['track']['name']
    song_duration = row['track']['duration_ms']
    song_url = row['track']['external_urls']['spotify']
    song_popularity = row['track']['popularity']
    song_added = row['added_at']
    album_id = row['track']['id']
    artist_id = row['track']['album']['id']
    song_element = {'song_id' : song_id,
                    'song_name' : song_name,
                    'song_duration' : song_duration,
                    'song_url' : song_url,
                    'song_popularity' : song_popularity,
                    'song_added' : song_added,
                    'album_id' : album_id,
                    'artist_id' : artist_id}
    songs_list.append(song_element)

In [107]:
album_df = pd.DataFrame.from_dict(album_list)

In [110]:
album_df.head()

,album_id,album_name,album_release_date,album_total_tracks,album_url
0,0I7096R74VFP2xnMmp33sY,PASSO BEM SOLTO,2024-04-23,5,https://open.spotify.com/album/0I7096R74VFP2xn...
1,7FsRROosPNliIsu3YzSs9n,MONTAGEM RUGADA,2025-08-27,6,https://open.spotify.com/album/7FsRROosPNliIsu...
2,5kB03HrxWnYPPB9BvwbYG1,NO BATIDÃO,2025-09-05,3,https://open.spotify.com/album/5kB03HrxWnYPPB9...
3,5k8jDV518pIk74gBsU72fi,MONTAGEM COMA,2025-06-06,4,https://open.spotify.com/album/5k8jDV518pIk74g...
4,6L63sOxoncxwRrf2ktyudM,OLHA MENSAGEM,2025-04-16,6,https://open.spotify.com/album/6L63sOxoncxwRrf...

In [111]:
album_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 88 entries, 0 to 87
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   album_id            88 non-null     str
 1   album_name          88 non-null     str
 2   album_release_date  88 non-null     str
 3   album_total_tracks  88 non-null     int64
 4   album_url           88 non-null     str
dtypes: int64(1), str(4)
memory usage: 3.6 KB

In [112]:
artist_df = pd.DataFrame.from_dict(artist_list)

In [113]:
artist_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 185 entries, 0 to 184
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   artist_id      185 non-null    str
 1   external_urls  185 non-null    str
 2   name           185 non-null    str
dtypes: str(3)
memory usage: 4.5 KB

In [116]:
song_df = pd.DataFrame.from_dict(songs_list)
song_df.head()

,song_id,song_name,song_duration,song_url,song_popularity,song_added,album_id,artist_id
0,4sTlQPMyoFMPdhAJvErBN3,PASSO BEM SOLTO - Slowed,116072,https://open.spotify.com/track/4sTlQPMyoFMPdhA...,82,2025-05-10T16:34:06Z,4sTlQPMyoFMPdhAJvErBN3,0I7096R74VFP2xnMmp33sY
1,7hCUHXMZknrymWCyeMx8B6,MONTAGEM RUGADA,92384,https://open.spotify.com/track/7hCUHXMZknrymWC...,84,2025-12-25T16:04:28Z,7hCUHXMZknrymWCyeMx8B6,7FsRROosPNliIsu3YzSs9n
2,72YttnPRxyHe8zCG50jYhj,NO BATIDÃO - Slowed,107933,https://open.spotify.com/track/72YttnPRxyHe8zC...,88,2025-12-25T16:03:57Z,72YttnPRxyHe8zCG50jYhj,5kB03HrxWnYPPB9BvwbYG1
3,2UbLtO7CH3jhez0n2T7uDC,MONTAGEM COMA,73480,https://open.spotify.com/track/2UbLtO7CH3jhez0...,80,2025-08-14T12:19:50Z,2UbLtO7CH3jhez0n2T7uDC,5k8jDV518pIk74gBsU72fi
4,4bRgPiewooIntAQfPx4sCG,OLHA MENSAGEM,100714,https://open.spotify.com/track/4bRgPiewooIntAQ...,69,2025-08-14T12:17:56Z,4bRgPiewooIntAQfPx4sCG,6L63sOxoncxwRrf2ktyudM

In [117]:
song_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 88 entries, 0 to 87
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   song_id          88 non-null     str
 1   song_name        88 non-null     str
 2   song_duration    88 non-null     int64
 3   song_url         88 non-null     str
 4   song_popularity  88 non-null     int64
 5   song_added       88 non-null     str
 6   album_id         88 non-null     str
 7   artist_id        88 non-null     str
dtypes: int64(2), str(6)
memory usage: 5.6 KB

In [120]:
song_df['song_added'] = pd.to_datetime(song_df['song_added'])
song_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 88 entries, 0 to 87
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   song_id          88 non-null     str
 1   song_name        88 non-null     str
 2   song_duration    88 non-null     int64
 3   song_url         88 non-null     str
 4   song_popularity  88 non-null     int64
 5   song_added       88 non-null     datetime64[us, UTC]
 6   album_id         88 non-null     str
 7   artist_id        88 non-null     str
dtypes: datetime64[us, UTC](1), int64(2), str(5)
memory usage: 5.6 KB

In [118]:
album_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 88 entries, 0 to 87
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   album_id            88 non-null     str
 1   album_name          88 non-null     str
 2   album_release_date  88 non-null     str
 3   album_total_tracks  88 non-null     int64
 4   album_url           88 non-null     str
dtypes: int64(1), str(4)
memory usage: 3.6 KB

In [119]:
album_df['album_release_date'] = pd.to_datetime(album_df['album_release_date'])
album_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 88 entries, 0 to 87
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   album_id            88 non-null     str
 1   album_name          88 non-null     str
 2   album_release_date  88 non-null     datetime64[us]
 3   album_total_tracks  88 non-null     int64
 4   album_url           88 non-null     str
dtypes: datetime64[us](1), int64(1), str(3)
memory usage: 3.6 KB

## spotifydata_extract

In [ ]:
import json
import os
import boto3
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
from datetime import datetime

def lambda_handler(event, context):
    SPOTIFY_CLIENT_ID = os.environ.get("SPOTIFY_CLIENT_ID")
    SPOTIFY_CLIENT_SECRET  = os.environ.get("SPOTIFY_CLIENT_SECRET")
    client_credentials_manager = SpotifyClientCredentials(client_id = SPOTIFY_CLIENT_ID, client_secret= SPOTIFY_CLIENT_SECRET)
    sp = spotipy.Spotify(client_credentials_manager=client_credentials_manager)
    playlists = sp.user_playlists('spotify')
    playlist_link = "https://open.spotify.com/playlist/6VOedaf3eNWDOVpa9Qdlvg"
    playlist_URI = playlist_link.split('/')[-1]
    data = sp.playlist_tracks(playlist_id=playlist_URI)
    filename = 'spotify_raw_' + str(datetime.now()) +'.json'
    client = boto3.client('s3')
    client.put_object(
        Bucket='spotify-etl-pipeline-sumanth-dec25',
        Key='raw_data/to_processed/' + filename,
        Body=json.dumps(data)
    )

## spotifydata_load_transformation

In [ ]:
import json
import boto3
from datetime import datetime
from io import StringIO
import pandas as pd 

def album(data):
    album_list = []
    for row in data['items']:
        album_id = row['track']['album']['id']
        album_name = row['track']['album']['name']
        album_release_date = row['track']['album']['release_date']
        album_total_tracks = row['track']['album']['total_tracks']
        album_url = row['track']['album']['external_urls']['spotify']
        album_element = {'album_id':album_id,'name':album_name,'release_date':album_release_date,
                            'total_tracks':album_total_tracks,'url':album_url}
        album_list.append(album_element)
    return album_list

def artist(data):
    artist_list = []
    for row in data['items']:
        for key, value in row.items():
            if key == "track":
                for artist in value['artists']:
                    artist_dict = {'artist_id':artist['id'], 'artist_name':artist['name'], 'external_url': artist['href']}
                    artist_list.append(artist_dict)
    return artist_list


def songs(data):
    song_list = []
    for row in data['items']:
        song_id = row['track']['id']
        song_name = row['track']['name']
        song_duration = row['track']['duration_ms']
        song_url = row['track']['external_urls']['spotify']
        song_popularity = row['track']['popularity']
        song_added = row['added_at']
        album_id = row['track']['album']['id']
        artist_id = row['track']['album']['artists'][0]['id']
        song_element = {'song_id':song_id,'song_name':song_name,'duration_ms':song_duration,'url':song_url,
                        'popularity':song_popularity,'song_added':song_added,'album_id':album_id,
                        'artist_id':artist_id
                       }
        song_list.append(song_element)
        
    return song_list

def lambda_handler(event, context):
    s3 = boto3.client('s3')
    Bucket = 'spotify-etl-pipeline-sumanth-dec25'
    Key = "raw_data/to_processed/"
    spotify_data = []
    spotify_keys = []
    for file in s3.list_objects(Bucket= Bucket, Prefix = Key)['Contents'] :
        file_key = file['Key']
        if file_key.split('.')[-1] =='json':
            response = s3.get_object(Bucket = Bucket, Key = file_key)
            content = response['Body']
            jsonObject = json.loads(content.read())
            spotify_data.append(jsonObject)
            spotify_keys.append(file_key)

    for data in spotify_data:
        album_list = album(data)
        artist_list = artist(data)
        song_list = songs(data)
        
        album_df = pd.DataFrame.from_dict(album_list)
        album_df = album_df.drop_duplicates(subset=['album_id'])
        
        artist_df = pd.DataFrame.from_dict(artist_list)
        artist_df = artist_df.drop_duplicates(subset=['artist_id'])
        
        #Song Dataframe
        song_df = pd.DataFrame.from_dict(song_list)
        
        album_df['release_date'] = pd.to_datetime(album_df['release_date'])
        song_df['song_added'] =  pd.to_datetime(song_df['song_added'])
        
        songs_key = "transformed_data/songs_data/songs_transformed_" + str(datetime.now()) + ".csv"
        song_buffer=StringIO()
        song_df.to_csv(song_buffer, index=False)
        song_content = song_buffer.getvalue()
        s3.put_object(Bucket=Bucket, Key=songs_key, Body=song_content)
        
        album_key = "transformed_data/album_data/album_transformed_" + str(datetime.now()) + ".csv"
        album_buffer=StringIO()
        album_df.to_csv(album_buffer, index=False)
        album_content = album_buffer.getvalue()
        s3.put_object(Bucket=Bucket, Key=album_key, Body=album_content)
        
        artist_key = "transformed_data/artist_data/artist_transformed_" + str(datetime.now()) + ".csv"
        artist_buffer=StringIO()
        artist_df.to_csv(artist_buffer, index=False)
        artist_content = artist_buffer.getvalue()
        s3.put_object(Bucket=Bucket, Key=artist_key, Body=artist_content)
        
    s3_resource = boto3.resource('s3')
    for key in spotify_keys:
        copy_source = {
            'Bucket': Bucket,
            'Key': key
        }
        s3_resource.meta.client.copy(copy_source, Bucket, 'raw_data/processed/' + key.split("/")[-1])    
        s3_resource.Object(Bucket, key).delete()